#pragma once

#include <sead/math/seadVector.h>

#include "Library/LiveActor/LiveActor.h"  // for SensorMsg

struct SaveObjInfo;
struct HackEndParam;
struct IUsePlayerCollision;
struct IUsePlayerHack;

struct DigPoint;
struct TouchTargetInfo;
struct WhipTargetInfo;
struct CapTargetInfo;
struct GotogotonMark;
struct FishingFish;

typedef unsigned int uint;

namespace al {
class HitSensor;
class HitSensorKeeper;
class HitSensorGroup;

struct ComboCounter;
struct EventFlowExecutor;
struct ParabolicPath;

sead::Vector3f* getActorTrans(const al::HitSensor*);
sead::Vector3f& getSensorPos(const al::HitSensor*);
float getSensorRadius(const al::HitSensor*);

void setSensorRadius(al::LiveActor*, const char*, float);

void invalidateHitSensor(al::LiveActor*, const char*);
void validateHitSensor(al::LiveActor*, const char*);

bool tryReceiveMsgPushAndAddVelocity(al::LiveActor*, const al::SensorMsg*, const al::HitSensor*, const al::HitSensor*, float);

bool isSensorTypeYoshiEnableSendPush(const al::HitSensor*);
bool isSensorTypeYoshiMsgReceivable(const al::HitSensor*);
bool isSensorValid(const al::HitSensor*);
bool isSensorName(const al::HitSensor*, const char*);
bool isSensorHostName(const al::HitSensor*, const char*);
bool isSensorHost(const al::HitSensor*, const al::LiveActor*);
bool isSensorValid(const al::LiveActor*, const char*);
bool isSensorBindableAll(const al::HitSensor*);
bool isSensorEnemy(const al::HitSensor*);
bool isSensorEnemyAttack(const al::HitSensor*);
bool isSensorEnemyBody(const al::HitSensor*);
bool isSensorEye(const al::HitSensor*);
bool isSensorMapObj(const al::HitSensor*);
bool isSensorNpc(const al::HitSensor*);
bool isSensorPlayerAll(const al::HitSensor*);
bool isSensorRide(const al::HitSensor*);
bool isSensorPlayerAttack(const al::HitSensor*);
bool isSensorPlayer(const al::HitSensor*);
bool isSensorPlayerFoot(const al::HitSensor*);
bool isSensorPlayerDecoration(const al::HitSensor*);
bool isSensorPlayerEye(const al::HitSensor*);
bool isSensorPlayerOrPlayerWeapon(const al::HitSensor*);
bool isSensorCollision(const al::HitSensor*);
bool isSensorPlayerFireBall(const al::HitSensor*);
bool isSensorHoldObj(const al::HitSensor*);
bool isSensorLookAt(const al::HitSensor*);
bool isSensorBindableGoal(const al::HitSensor*);
bool isSensorBindableAllPlayer(const al::HitSensor*);
bool isSensorBindableBubbleOutScreen(const al::HitSensor*);
bool isSensorBindableKoura(const al::HitSensor*);
bool isSensorBindableRouteDokan(const al::HitSensor*);
bool isSensorBindableBubblePadInput(const al::HitSensor*);
bool isSensorBindable(const al::HitSensor*);
bool isSensorSimple(const al::HitSensor*);
bool isSensorHitAnyPlane(const al::HitSensor*, const al::HitSensor*, const sead::Vector3<float>&);
bool isSensorHitRingShape(const al::HitSensor*, const al::HitSensor*, float);

bool isMsgRequestPlayerStainWet(const al::SensorMsg*, int*);
bool isMsgPushAll(const al::SensorMsg*);
bool isMsgPush(const al::SensorMsg*);
bool isMsgPushStrong(const al::SensorMsg*);
bool isMsgPushVeryStrong(const al::SensorMsg*);
bool isMsgHoldReleaseAll(const al::SensorMsg*);
bool isMsgHoldCancel(const al::SensorMsg*);
bool isMsgPlayerRelease(const al::SensorMsg*);
bool isMsgPlayerReleaseBySwing(const al::SensorMsg*);
bool isMsgPlayerReleaseDead(const al::SensorMsg*);
bool isMsgPlayerReleaseDamage(const al::SensorMsg*);
bool isMsgPlayerReleaseDemo(const al::SensorMsg*);
bool isMsgItemGetDirectAll(const al::SensorMsg*);
bool isMsgPlayerItemGet(const al::SensorMsg*);
bool isMsgRideAllPlayerItemGet(const al::SensorMsg*);
bool isMsgPlayerTailAttack(const al::SensorMsg*);
bool isMsgItemGetByObjAll(const al::SensorMsg*);
bool isMsgBallItemGet(const al::SensorMsg*);
bool isMsgKickKouraItemGet(const al::SensorMsg*);
bool isMsgKillerItemGet(const al::SensorMsg*);
bool isMsgItemGetAll(const al::SensorMsg*);
bool isMsgFloorTouch(const al::SensorMsg*);
bool isMsgPlayerFloorTouch(const al::SensorMsg*);
bool isMsgEnemyFloorTouch(const al::SensorMsg*);
bool isMsgUpperPunch(const al::SensorMsg*);
bool isMsgPlayerUpperPunch(const al::SensorMsg*);
bool isMsgEnemyUpperPunch(const al::SensorMsg*);
bool isMsgPlayerTrample(const al::SensorMsg*);
bool isMsgPlayerTrampleReflect(const al::SensorMsg*);
bool isMsgPlayerHipDropAll(const al::SensorMsg*);
bool isMsgPlayerStatueDrop(const al::SensorMsg*);
bool isMsgPlayerObjHipDropAll(const al::SensorMsg*);
bool isMsgPlayerObjStatueDrop(const al::SensorMsg*);
bool isMsgPlayerObjHipDropReflectAll(const al::SensorMsg*);
bool isMsgPlayerObjStatueDropReflect(const al::SensorMsg*);
bool isMsgPlayerObjHipDropHighJump(const al::SensorMsg*);
bool isMsgPlayerHipDropKnockDown(const al::SensorMsg*);
bool isMsgPlayerObjStatueDropReflectNoCondition(const al::SensorMsg*);
bool isMsgPlayerStatueTouch(const al::SensorMsg*);
bool isMsgPlayerObjUpperPunch(const al::SensorMsg*);
bool isMsgPlayerRollingAttack(const al::SensorMsg*);
bool isMsgPlayerRollingReflect(const al::SensorMsg*);
bool isMsgPlayerObjRollingAttack(const al::SensorMsg*);
bool isMsgPlayerObjRollingAttackFailure(const al::SensorMsg*);
bool isMsgPlayerInvincibleAttack(const al::SensorMsg*);
bool isMsgPlayerFireBallAttack(const al::SensorMsg*);
bool isMsgPlayerRouteDokanFireBallAttack(const al::SensorMsg*);
bool isMsgPlayerKick(const al::SensorMsg*);
bool isMsgPlayerCatch(const al::SensorMsg*);
bool isMsgPlayerSlidingAttack(const al::SensorMsg*);
bool isMsgPlayerBoomerangAttack(const al::SensorMsg*);
bool isMsgPlayerBoomerangAttackCollide(const al::SensorMsg*);
bool isMsgPlayerBoomerangReflect(const al::SensorMsg*);
bool isMsgPlayerBoomerangBreak(const al::SensorMsg*);
bool isMsgPlayerBodyAttack(const al::SensorMsg*);
bool isMsgPlayerBodyLanding(const al::SensorMsg*);
bool isMsgPlayerBodyAttackReflect(const al::SensorMsg*);
bool isMsgPlayerClimbAttack(const al::SensorMsg*);
bool isMsgPlayerSpinAttack(const al::SensorMsg*);
bool isMsgPlayerGiantAttack(const al::SensorMsg*);
bool isMsgPlayerCooperationHipDrop(const al::SensorMsg*);
bool isMsgPlayerClimbSlidingAttack(const al::SensorMsg*);
bool isMsgPlayerClimbRollingAttack(const al::SensorMsg*);
bool isMsgPlayerGiantHipDrop(const al::SensorMsg*);
bool isMsgPlayerDisregard(const al::SensorMsg*);
bool isMsgPlayerDash(const al::SensorMsg*);
bool isMsgPlayerDamageTouch(const al::SensorMsg*);
bool isMsgPlayerFloorTouchBind(const al::SensorMsg*);
bool isMsgPlayerTouch(const al::SensorMsg*);
bool isMsgPlayerInvincibleTouch(const al::SensorMsg*);
bool isMsgPlayerGiantTouch(const al::SensorMsg*);
bool isMsgPlayerObjTouch(const al::SensorMsg*);
bool isMsgPlayerPutOnEquipment(const al::SensorMsg*);
bool isMsgPlayerReleaseEquipment(const al::SensorMsg*);
bool isMsgPlayerReleaseEquipmentGoal(const al::SensorMsg*);
bool isMsgPlayerCarryFront(const al::SensorMsg*);
bool isMsgPlayerCarryFrontWallKeep(const al::SensorMsg*);
bool isMsgPlayerCarryUp(const al::SensorMsg*);
bool isMsgPlayerCarryKeepDemo(const al::SensorMsg*);
bool isMsgPlayerCarryWarp(const al::SensorMsg*);
bool isMsgPlayerLeave(const al::SensorMsg*);
bool isMsgPlayerToss(const al::SensorMsg*);
bool isMsgEnemyAttack(const al::SensorMsg*);
bool isMsgEnemyAttackFire(const al::SensorMsg*);
bool isMsgEnemyAttackKnockDown(const al::SensorMsg*);
bool isMsgEnemyAttackBoomerang(const al::SensorMsg*);
bool isMsgEnemyAttackNeedle(const al::SensorMsg*);
bool isMsgEnemyItemGet(const al::SensorMsg*);
bool isMsgEnemyRouteDokanAttack(const al::SensorMsg*);
bool isMsgEnemyRouteDokanFire(const al::SensorMsg*);
bool isMsgExplosion(const al::SensorMsg*);
bool isMsgExplosionCollide(const al::SensorMsg*);
bool isMsgBindStart(const al::SensorMsg*);
bool isMsgBindInit(const al::SensorMsg*);
bool isMsgBindEnd(const al::SensorMsg*);
bool isMsgBindCancel(const al::SensorMsg*);
bool isMsgBindCancelByDemo(const al::SensorMsg*);
bool isMsgBindDamage(const al::SensorMsg*);
bool isMsgBindSteal(const al::SensorMsg*);
bool isMsgBindGiant(const al::SensorMsg*);
bool isMsgPressureDeath(const al::SensorMsg*);
bool isMsgNpcTouch(const al::SensorMsg*);
bool isMsgHit(const al::SensorMsg*);
bool isMsgHitStrong(const al::SensorMsg*);
bool isMsgHitVeryStrong(const al::SensorMsg*);
bool isMsgKnockDown(const al::SensorMsg*);
bool isMsgMapPush(const al::SensorMsg*);
bool isMsgVanish(const al::SensorMsg*);
bool isMsgChangeAlpha(const al::SensorMsg*);
bool isMsgShowModel(const al::SensorMsg*);
bool isMsgHideModel(const al::SensorMsg*);
bool isMsgRestart(const al::SensorMsg*);
bool isMsgEnemyTouch(const al::SensorMsg*);
bool isMsgEnemyTrample(const al::SensorMsg*);
bool isMsgMapObjTrample(const al::SensorMsg*);
bool isMsgNeedleBallAttack(const al::SensorMsg*);
bool isMsgPunpunFloorTouch(const al::SensorMsg*);
bool isMsgInvalidateFootPrint(const al::SensorMsg*);
bool isMsgKickKouraAttack(const al::SensorMsg*);
bool isMsgKickKouraAttackCollide(const al::SensorMsg*);
bool isMsgKickKouraReflect(const al::SensorMsg*);
bool isMsgKickKouraCollideNoReflect(const al::SensorMsg*);
bool isMsgKickKouraBreak(const al::SensorMsg*);
bool isMsgKickKouraBlow(const al::SensorMsg*);
bool isMsgKickStoneAttack(const al::SensorMsg*);
bool isMsgKickStoneAttackCollide(const al::SensorMsg*);
bool isMsgKickStoneAttackHold(const al::SensorMsg*);
bool isMsgKickStoneAttackReflect(const al::SensorMsg*);
bool isMsgKickStoneTrample(const al::SensorMsg*);
bool isMsgKillerAttack(const al::SensorMsg*);
bool isMsgLiftGeyser(const al::SensorMsg*);
bool isMsgWarpStart(const al::SensorMsg*);
bool isMsgWarpEnd(const al::SensorMsg*);
bool isMsgHoleIn(const al::SensorMsg*);
bool isMsgJumpInhibit(const al::SensorMsg*);
bool isMsgGoalKill(const al::SensorMsg*);
bool isMsgGoal(const al::SensorMsg*);
bool isMsgBallAttack(const al::SensorMsg*);
bool isMsgBallRouteDokanAttack(const al::SensorMsg*);
bool isMsgBallAttackHold(const al::SensorMsg*);
bool isMsgBallAttackDRCHold(const al::SensorMsg*);
bool isMsgBallAttackCollide(const al::SensorMsg*);
bool isMsgBallTrample(const al::SensorMsg*);
bool isMsgBallTrampleCollide(const al::SensorMsg*);
bool isMsgFireBallCollide(const al::SensorMsg*);
bool isMsgFireBallFloorTouch(const al::SensorMsg*);
bool isMsgDokanBazookaAttack(const al::SensorMsg*);
bool isMsgSwitchOn(const al::SensorMsg*);
bool isMsgSwitchOnInit(const al::SensorMsg*);
bool isMsgSwitchOffInit(const al::SensorMsg*);
bool isMsgSwitchKillOn(const al::SensorMsg*);
bool isMsgSwitchKillOnInit(const al::SensorMsg*);
bool isMsgSwitchKillOffInit(const al::SensorMsg*);
bool isMsgAskSafetyPoint(const al::SensorMsg*);
bool isMsgTouchAssist(const al::SensorMsg*);
bool isMsgTouchAssistNoPat(const al::SensorMsg*);
bool isMsgTouchAssistTrig(const al::SensorMsg*);
bool isMsgTouchAssistTrigOff(const al::SensorMsg*);
bool isMsgTouchAssistTrigNoPat(const al::SensorMsg*);
bool isMsgTouchAssistBurn(const al::SensorMsg*);
bool isMsgTouchAssistAll(const al::SensorMsg*);
bool isMsgTouchCarryItem(const al::SensorMsg*);
bool isMsgTouchReleaseItem(const al::SensorMsg*);
bool isMsgTouchStroke(const al::SensorMsg*);
bool isMsgIsNerveSupportFreeze(const al::SensorMsg*);
bool isMsgOnSyncSupportFreeze(const al::SensorMsg*);
bool isMsgOffSyncSupportFreeze(const al::SensorMsg*);
bool isMsgScreenPointInvalidCollisionParts(const al::SensorMsg*);
bool isMsgBlockUpperPunch(const al::SensorMsg*);
bool isMsgBlockLowerPunch(const al::SensorMsg*);
bool isMsgBlockItemGet(const al::SensorMsg*);
bool isMsgPlayerKouraAttack(const al::SensorMsg*);
bool isMsgLightFlash(const al::SensorMsg*);
bool isMsgForceAbyss(const al::SensorMsg*);
bool isMsgSwordAttackHigh(const al::SensorMsg*);
bool isMsgSwordAttackHighLeft(const al::SensorMsg*);
bool isMsgSwordAttackHighRight(const al::SensorMsg*);
bool isMsgSwordAttackLow(const al::SensorMsg*);
bool isMsgSwordAttackLowLeft(const al::SensorMsg*);
bool isMsgSwordAttackLowRight(const al::SensorMsg*);
bool isMsgSwordBeamAttack(const al::SensorMsg*);
bool isMsgSwordBeamReflectAttack(const al::SensorMsg*);
bool isMsgSwordAttackJumpUnder(const al::SensorMsg*);
bool isMsgShieldGuard(const al::SensorMsg*);
bool isMsgAskMultiPlayerEnemy(const al::SensorMsg*);
bool isMsgItemGettable(const al::SensorMsg*);
bool isMsgKikkiThrow(const al::SensorMsg*);
bool isMsgIsKikkiThrowTarget(const al::SensorMsg*);
bool isMsgPlayerCloudGet(const al::SensorMsg*);
bool isMsgAutoJump(const al::SensorMsg*);
bool isMsgPlayerTouchShadow(const al::SensorMsg*);
bool isMsgPlayerPullOutShadow(const al::SensorMsg*);
bool isMsgPlayerAttackShadow(const al::SensorMsg*);
bool isMsgPlayerAttackShadowStrong(const al::SensorMsg*);
bool isMsgPlayerAttackChangePos(const al::SensorMsg*);
bool isMsgAtmosOnlineLight(const al::SensorMsg*);
bool isMsgLightBurn(const al::SensorMsg*);
bool isMsgMoonLightBurn(const al::SensorMsg*);
bool isMsgString(const al::SensorMsg*);
bool isMsgStringV4fPtr(const al::SensorMsg*);
bool isMsgStringV4fSensorPtr(const al::SensorMsg*);
bool isMsgStringVoidPtr(const al::SensorMsg*);
bool isMsgPlayerTrampleForCrossoverSensor(const al::SensorMsg*, const al::HitSensor*, const al::HitSensor*);
bool isMsgPlayerTrampleReflectForCrossoverSensor(const al::SensorMsg*, const al::HitSensor*, const al::HitSensor*);
bool isMsgPlayerUpperPunchForCrossoverSensor(const al::SensorMsg*, const al::HitSensor*, const al::HitSensor*, float);
bool isMsgKickStoneTrampleForCrossoverSensor(const al::SensorMsg*, const al::HitSensor*, const al::HitSensor*);

bool sendMsgPlayerAttackTrample(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerTrampleReflect(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerReflectOrTrample(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerHipDrop(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerObjHipDrop(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerObjHipDropReflect(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerObjHipDropHighJump(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerHipDropKnockDown(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerStatueDrop(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerObjStatueDrop(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerObjStatueDropReflect(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerObjStatueDropReflectNoCondition(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerStatueTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerUpperPunch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerObjUpperPunch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRollingAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRollingReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerObjRollingAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerObjRollingAttackFailure(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerInvincibleAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerFireBallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRouteDokanFireBallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerTailAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerKick(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCatch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerSlidingAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerBoomerangAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerBoomerangAttackCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerBoomerangReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerBoomerangBreak(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerBodyAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerBodyLanding(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerBodyAttackReflect(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerClimbAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerSpinAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerGiantAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerCooperationHipDrop(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerClimbSlidingAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerClimbRollingAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerGiantHipDrop(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerDisregard(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerPutOnEquipment(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerReleaseEquipment(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerReleaseEquipmentGoal(al::HitSensor*, al::HitSensor*, uint);
bool sendMsgPlayerFloorTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerDamageTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryFront(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryFrontWallKeep(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryUp(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryKeepDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryWarp(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerLeave(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRelease(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerReleaseBySwing(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerReleaseDamage(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerReleaseDead(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerReleaseDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerToss(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerInvincibleTouch(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgEnemyAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackBoomerang(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackFire(al::HitSensor*, al::HitSensor*, const char*);
bool sendMsgEnemyAttackNeedle(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyFloorTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyRouteDokanAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyRouteDokanFire(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyUpperPunch(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgMapObjTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgPressureDeath(al::HitSensor*, al::HitSensor*);
bool sendMsgNpcTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgExplosion(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgExplosionCollide(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPush(al::HitSensor*, al::HitSensor*);
bool sendMsgPushStrong(al::HitSensor*, al::HitSensor*);
bool sendMsgPushVeryStrong(al::HitSensor*, al::HitSensor*);
bool sendMsgHit(al::HitSensor*, al::HitSensor*);
bool sendMsgHitStrong(al::HitSensor*, al::HitSensor*);
bool sendMsgHitVeryStrong(al::HitSensor*, al::HitSensor*);
bool sendMsgKnockDown(al::HitSensor*, al::HitSensor*);
bool sendMsgMapPush(al::HitSensor*, al::HitSensor*);
bool sendMsgVanish(al::HitSensor*, al::HitSensor*);
bool sendMsgChangeAlpha(al::LiveActor*, float);
bool sendMsgShowModel(al::HitSensor*, al::HitSensor*);
bool sendMsgHideModel(al::HitSensor*, al::HitSensor*);
bool sendMsgRestart(al::HitSensor*, al::HitSensor*);
bool sendMsgNeedleBallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPunpunFloorTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgInvalidateFootPrint(al::HitSensor*, al::HitSensor*);
bool sendMsgKickKouraAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgKickKouraAttackCollide(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgKickKouraGetItem(al::HitSensor*, al::HitSensor*);
bool sendMsgKickKouraReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgKickKouraCollideNoReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgKickKouraBreak(al::HitSensor*, al::HitSensor*);
bool sendMsgKickKouraBlow(al::HitSensor*, al::HitSensor*);
bool sendMsgKickStoneAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKickStoneAttackCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgKickStoneAttackHold(al::HitSensor*, al::HitSensor*);
bool sendMsgKickStoneAttackReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgKickStoneTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgKillerAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgLiftGeyser(al::HitSensor*, al::HitSensor*);
bool sendMsgWarpStart(al::HitSensor*, al::HitSensor*);
bool sendMsgWarpEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgHoldCancel(al::HitSensor*, al::HitSensor*);
bool sendMsgHoleIn(al::HitSensor*, al::HitSensor*);
bool sendMsgJumpInhibit(al::HitSensor*, al::HitSensor*);
bool sendMsgGoalKill(al::HitSensor*, al::HitSensor*);
bool sendMsgGoal(al::HitSensor*, al::HitSensor*);
bool sendMsgBindStart(al::HitSensor*, al::HitSensor*);
bool sendMsgBindInit(al::HitSensor*, al::HitSensor*, uint);
bool sendMsgBindEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgBindCancel(al::HitSensor*, al::HitSensor*);
bool sendMsgBindCancelByDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgBindDamage(al::HitSensor*, al::HitSensor*);
bool sendMsgBindSteal(al::HitSensor*, al::HitSensor*);
bool sendMsgBindGiant(al::HitSensor*, al::HitSensor*);
bool sendMsgBallAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgBallRouteDokanAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgBallAttackHold(al::HitSensor*, al::HitSensor*);
bool sendMsgBallAttackDRCHold(al::HitSensor*, al::HitSensor*);
bool sendMsgBallAttackCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgBallTrample(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgBallTrampleCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgBallItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgFireBalCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgFireBallFloorTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgDokanBazookaAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgRideAllPlayerItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgHideModel(al::LiveActor*);
bool sendMsgShowModel(al::LiveActor*);
bool sendMsgRestart(al::LiveActor*);
bool sendMsgCollisionImpulse(al::HitSensor*, al::HitSensor*, sead::Vector3f*, const sead::Vector3f&, float, const sead::Vector3f&, float);
bool sendMsgSwitchOn(al::LiveActor*);
bool sendMsgSwitchOnInit(al::LiveActor*);
bool sendMsgSwitchOffInit(al::LiveActor*);
bool sendMsgSwitchKillOn(al::LiveActor*);
bool sendMsgSwitchKillOnInit(al::LiveActor*);
bool sendMsgSwitchKillOffInit(al::LiveActor*);
bool sendMsgPlayerFloorTouchToColliderGround(al::LiveActor*, al::HitSensor*);
bool sendMsgPlayerUpperPunchToColliderCeiling(al::LiveActor*, al::HitSensor*);
bool sendMsgEnemyFloorTouchToColliderGround(al::LiveActor*, al::HitSensor*);
bool sendMsgEnemyUpperPunchToColliderCeiling(al::LiveActor*, al::HitSensor*);
bool sendMsgAskSafetyPoint(al::HitSensor*, al::HitSensor*, sead::Vector3f**);
bool sendMsgAskSafetyPointToColliderGround(al::LiveActor*, al::HitSensor*, sead::Vector3f**);
bool sendMsgTouchAssist(al::HitSensor*, al::HitSensor*);
bool sendMsgTouchAssistTrig(al::HitSensor*, al::HitSensor*);
bool sendMsgTouchStroke(al::HitSensor*, al::HitSensor*);
bool sendMsgScreenPointInvalidCollisionParts(al::HitSensor*, al::HitSensor*);
bool sendMsgBlockUpperPunch(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgBlockLowerPunch(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgBlockItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgKillerItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerKouraAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgLightFlash(al::HitSensor*, al::HitSensor*);
bool sendMsgForceAbyss(al::HitSensor*, al::HitSensor*);
bool sendMsgIsNerveSupportFreeze(al::HitSensor*, al::HitSensor*);
bool sendMsgOnSyncSupportFreeze(al::HitSensor*, al::HitSensor*);
bool sendMsgOffSyncSupportFreeze(al::HitSensor*, al::HitSensor*);
bool sendMsgSwordAttackHighLeft(al::HitSensor*, al::HitSensor*);
bool sendMsgSwordAttackLowLeft(al::HitSensor*, al::HitSensor*);
bool sendMsgSwordAttackHighRight(al::HitSensor*, al::HitSensor*);
bool sendMsgSwordAttackLowRight(al::HitSensor*, al::HitSensor*);
bool sendMsgSwordAttackJumpUnder(al::HitSensor*, al::HitSensor*);
bool sendMsgSwordBeamAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgSwordBeamReflectAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgShieldGuard(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackKnockDown(al::HitSensor*, al::HitSensor*);
bool sendMsgAskMultiPlayerEnemy(al::HitSensor*, al::HitSensor*);
bool sendMsgItemGettable(al::HitSensor*, al::HitSensor*);
bool sendMsgKikkiThrow(al::HitSensor*, al::HitSensor*);
bool sendMsgIsKikkiThrowTarget(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCloudGet(al::HitSensor*, al::HitSensor*);
bool sendMsgAutoJump(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerTouchShadow(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerPullOutShadow(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerAttackShadow(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerAttackShadowStrong(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerAttackChangePos(al::HitSensor*, al::HitSensor*, sead::Vector3f*);
bool sendMsgAtmosOnlineLight(al::HitSensor*, al::HitSensor*);
bool sendMsgLightBurn(al::HitSensor*, al::HitSensor*);
bool sendMsgMoonLightBurn(al::HitSensor*, al::HitSensor*);
bool sendMsgString(al::HitSensor*, al::HitSensor*, const char*);
bool sendMsgStringV4fPtr(al::HitSensor*, al::HitSensor*, const char*, sead::Vector4f*);
bool sendMsgStringV4fSensorPtr(al::HitSensor*, al::HitSensor*, const char*, sead::Vector4f*);
bool sendMsgStringVoidPtr(al::HitSensor*, al::HitSensor*, const char*, void*);
bool sendMsgEnemyAttackForCrossoverSensor(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackForCrossoverCylinderSensor(al::HitSensor*, al::HitSensor*, const sead::Vector3f&, const sead::Vector3f&, float);
bool sendMsgPushAndKillVelocityToTarget(al::LiveActor*, al::HitSensor*, al::HitSensor*);
bool sendMsgPushAndKillVelocityToTargetH(al::LiveActor*, al::HitSensor*, al::HitSensor*);
bool sendMsgCollidePush(al::HitSensor*, al::HitSensor*, const sead::Vector3f&);
bool sendMsgScreenPointTarget(const al::SensorMsg&, al::ScreenPointer*, al::ScreenPointTarget*);

}  // namespace al
