#pragma once

#include <sead/math/seadVector.h>

#include "Library/LiveActor/LiveActor.h"  // for SensorMsg

#include "game/Player/IUsePlayerCollision.h"

namespace al {
class ComboCounter;
class ParabolicPath;
class EventFlowExecutor;
class HitSensor;
class HitSensorGroup;
}  // namespace al

namespace rs {

void setAppearItemFactorAndOffsetByMsg(const al::LiveActor*, const al::SensorMsg*, const al::HitSensor*);

bool isMsgBreakBySword(const al::SensorMsg*);
bool isMsgStatueDrop(const al::SensorMsg*);
bool isMsgHackerDamageAndCancel(const al::SensorMsg*);
bool isMsgEnableMapCheckPointWarpCollidedGround(const al::SensorMsg*, const al::LiveActor*);
bool isMsgEnableMapCheckPointWarpCollidedGround(const al::SensorMsg*, const IUsePlayerCollision*);
bool isMsgAckCheckpoint(const al::SensorMsg*);
bool isMsgAckGetShine(const al::SensorMsg*);
bool isMsgAckLifeUp(const al::SensorMsg*);
bool isMsgAckLifeMaxUp(const al::SensorMsg*);
bool isMsgAskRailCollision(const al::SensorMsg*);
bool isMsgAttachCactusNeedle(const al::SensorMsg*);
bool isMsgAirExplosion(const al::SensorMsg*);
bool isMsgBelowObjBroken(const al::SensorMsg*);
bool isMsgBindCollidedGround(const al::SensorMsg*);
bool isMsgBindKeepDemoStart(const al::SensorMsg*);
bool isMsgBindKeepDemoExecute(const al::SensorMsg*);
bool isMsgBindKeepDemoEnd(const al::SensorMsg*);
bool isMsgBindRecoveryLife(const al::SensorMsg*);
bool isMsgBirdFlyAway(const al::SensorMsg*);
bool isMsgBlowObjAttack(const al::SensorMsg*);
bool isMsgMayorItemCollide(const al::SensorMsg*);
bool isMsgMayorItemReflect(const al::SensorMsg*);
bool isMsgBlowObjAttackReflect(const al::SensorMsg*);
bool isMsgBossKnuckleCounter(const al::SensorMsg*);
bool isMsgBossKnuckleFallAttack(const al::SensorMsg*);
bool isMsgBossKnuckleHackAttack(const al::SensorMsg*);
bool isMsgBossKnuckleIceConflict(const al::SensorMsg*);
bool isMsgBossKnuckleIceFallToMummy(const al::SensorMsg*);
bool isMsgBossKnuckleKillerAttack(const al::SensorMsg*);
bool isMsgBreakPartsBreak(const al::SensorMsg*);
bool isMsgBreedaSlap(const al::SensorMsg*);
bool isMsgBreedaPush(const al::SensorMsg*);
bool isMsgBubbleAttack(const al::SensorMsg*);
bool isMsgBubbleAttackToPecho(const al::SensorMsg*);
bool isMsgBubbleLauncherStart(const al::SensorMsg*);
bool isMsgBubbleReflectH(const al::SensorMsg*);
bool isMsgBubbleReflectV(const al::SensorMsg*);
bool isMsgBubbleWallTouch(const al::SensorMsg*);
bool isMsgBubbleGroundTouchTrigger(const al::SensorMsg*);
bool isMsgBullAttack(const al::SensorMsg*);
bool isMsgBullHackAttack(const al::SensorMsg*);
bool isMsgBullEnemyAttack(const al::SensorMsg*);
bool isMsgByugoBlow(const al::SensorMsg*);
bool isMsgCameraAngleElevationResetFast(const al::SensorMsg*);
bool isMsgCancelHack(const al::SensorMsg*);
bool isMsgCancelHackArea(const al::SensorMsg*);
bool isMsgCancelHackByDokan(const al::SensorMsg*);
bool isMsgCapAttack(const al::SensorMsg*);
bool isMsgCapAttackCollide(const al::SensorMsg*);
bool isMsgCapAttackRailMove(const al::SensorMsg*);
bool isMsgCapAttackStayRolling(const al::SensorMsg*);
bool isMsgCapAttackStayRollingCollide(const al::SensorMsg*);
bool isMsgCapBeamerBeam(const al::SensorMsg*);
bool isMsgCapCancelLockOn(const al::SensorMsg*);
bool isMsgCapChangeGiant(const al::SensorMsg*);
bool isMsgCapEnableLockOn(const al::SensorMsg*);
bool isMsgCapStartLockOn(const al::SensorMsg*);
bool isMsgCapKeepLockOn(const al::SensorMsg*);
bool isMsgCapGiantAttack(const al::SensorMsg*);
bool isMsgCapHipDrop(const al::SensorMsg*);
bool isMsgCapObjHipDrop(const al::SensorMsg*);
bool isMsgCapObjHipDropReflect(const al::SensorMsg*);
bool isMsgCapIgnoreCancelLockOn(const al::SensorMsg*);
bool isMsgCapIgnoreCancelMissReaction(const al::SensorMsg*);
bool isMsgCapIgnoreCollisionCheck(const al::SensorMsg*);
bool isMsgCapItemGet(const al::SensorMsg*);
bool isMsgCapReflect(const al::SensorMsg*);
bool isMsgCapReflectCollide(const al::SensorMsg*);
bool isMsgCapRethrow(const al::SensorMsg*);
bool isMsgCapTouchWall(const al::SensorMsg*);
bool isMsgCapTrampolineAttack(const al::SensorMsg*);
bool isMsgCatchBombThrough(const al::SensorMsg*);
bool isMsgCheckCarObstacle(const al::SensorMsg*);
bool isMsgCheckIsCardboardBox(const al::SensorMsg*);
bool isMsgChorobonAttack(const al::SensorMsg*);
bool isMsgClearFire(const al::SensorMsg*);
bool isMsgCollectAnimalTouchCollide(const al::SensorMsg*);
bool isMsgCollisionImpulse(const al::SensorMsg*);
bool isMsgConductLightning(const al::SensorMsg*);
bool isMsgConfirmFrailBox(const al::SensorMsg*);
bool isMsgConfirmBrokenFrailBox(const al::SensorMsg*);
bool isMsgDamageBallAttack(const al::SensorMsg*);
bool isMsgDamageBallBodyAttack(const al::SensorMsg*);
bool isMsgDigPointSmell(const al::SensorMsg*);
bool isMsgDonsukeAttack(const al::SensorMsg*);
bool isMsgDonsukeGroundAttack(const al::SensorMsg*);
bool isMsgDonsukePush(const al::SensorMsg*);
bool isMsgDragonAttack(const al::SensorMsg*);
bool isMsgEatExplosion(const al::SensorMsg*);
bool isMsgElectricWireNoLimitDistance(const al::SensorMsg*);
bool isMsgEnableInSaucePan(const al::SensorMsg*);
bool isMsgEnableMapCheckPointWarp(const al::SensorMsg*);
bool isMsgEndInSaucePan(const al::SensorMsg*);
bool isMsgEnemyAttack2D(const al::SensorMsg*);
bool isMsgEnemyAttack3D(const al::SensorMsg*);
bool isMsgEnemyAttackDash(const al::SensorMsg*);
bool isMsgFireBrosFireBallCollide(const al::SensorMsg*);
bool isMsgFireDamageAll(const al::SensorMsg*);
bool isMsgHackAttackFire(const al::SensorMsg*);
bool isMsgFireSwitchFire(const al::SensorMsg*);
bool isMsgEnemyAttackFireCollision(const al::SensorMsg*);
bool isMsgEnemyAttackTRex(const al::SensorMsg*);
bool isMsgPoisonDamageAll(const al::SensorMsg*);
bool isMsgEnemyAttackPoison(const al::SensorMsg*);
bool isMsgHackAttackPoison(const al::SensorMsg*);
bool isMsgPaintAttackPoison(const al::SensorMsg*);
bool isMsgConfirmPaintObj(const al::SensorMsg*);
bool isMsgConfirmPaintObjForSeed(const al::SensorMsg*);
bool isMsgEnemyAttackStrong(const al::SensorMsg*);
bool isMsgEnemyKick(const al::SensorMsg*);
bool isMsgRabbitKick(const al::SensorMsg*);
bool isMsgEnemyObjBreak(const al::SensorMsg*);
bool isMsgFireBlowerAttack(const al::SensorMsg*);
bool isMsgFishingAttack(const al::SensorMsg*);
bool isMsgFishingCancel(const al::SensorMsg*);
bool isMsgFishingFishApproach(const al::SensorMsg*);
bool isMsgFishingFishFloatTouch(const al::SensorMsg*);
bool isMsgFishingItemGet(const al::SensorMsg*);
bool isMsgFishingLineTouch(const al::SensorMsg*);
bool isMsgFishingStart(const al::SensorMsg*);
bool isMsgFishingUpImmediately(const al::SensorMsg*);
bool isMsgFishingUpImmediatelyPrepare(const al::SensorMsg*);
bool isMsgFishingWait(const al::SensorMsg*);
bool isMsgFrogHackTrample(const al::SensorMsg*);
bool isMsgGamaneBullet(const al::SensorMsg*);
bool isMsgGamaneBulletThrough(const al::SensorMsg*);
bool isMsgGamaneBulletForCoinFlower(const al::SensorMsg*);
bool isMsgGemyAim(const al::SensorMsg*);
bool isMsgGhostCancel(const al::SensorMsg*);
bool isMsgGhostPlay(const al::SensorMsg*);
bool isMsgGhostRecordEnd(const al::SensorMsg*);
bool isMsgGhostRecordStart(const al::SensorMsg*);
bool isMsgGhostRecordStartOk(const al::SensorMsg*);
bool isMsgGhostReverse(const al::SensorMsg*);
bool isMsgGhostStop(const al::SensorMsg*);
bool isMsgGiantWanderBossAttack(const al::SensorMsg*);
bool isMsgGiantWanderBossBulletAttack(const al::SensorMsg*);
bool isMsgGiantWanderBossBulletPush(const al::SensorMsg*);
bool isMsgGoldHammerAttack(const al::SensorMsg*);
bool isMsgGrowFlowerSeedDisablePush(const al::SensorMsg*);
bool isMsgGrowFlowerSeedNear(const al::SensorMsg*);
bool isMsgGrowPlantPush(const al::SensorMsg*);
bool isMsgGrowerAttack(const al::SensorMsg*);
bool isMsgGrowerWallAttack(const al::SensorMsg*);
bool isMsgGunetterAttack(const al::SensorMsg*);
bool isMsgGunetterBodyTouch(const al::SensorMsg*);
bool isMsgGunetterPush(const al::SensorMsg*);
bool isMsgHackAttack(const al::SensorMsg*);
bool isMsgHackAttackKick(const al::SensorMsg*);
bool isMsgHackAttackMapObj(const al::SensorMsg*);
bool isMsgHackBrosContact(const al::SensorMsg*);
bool isMsgHackDeathAreaSelfCheck(const al::SensorMsg*);
bool isMsgHackDemoEnd(const al::SensorMsg*);
bool isMsgHackDemoStart(const al::SensorMsg*);
bool isMsgHackInvalidEscape(const al::SensorMsg*);
bool isMsgHackInvalidEscapeNoReaction(const al::SensorMsg*);
bool isMsgHackMarioCheckpointFlagWarp(const al::SensorMsg*);
bool isMsgHackMarioDead(const al::SensorMsg*);
bool isMsgHackMarioDemo(const al::SensorMsg*);
bool isMsgHackMarioInWater(const al::SensorMsg*);
bool isMsgHackMoveRockForestPush(const al::SensorMsg*);
bool isMsgHackSelfCeilingCheckMiss(const al::SensorMsg*);
bool isMsgHackSyncDamageVisibility(const al::SensorMsg*);
bool isMsgHackUpperPunch(const al::SensorMsg*);
bool isMsgHackObjUpperPunch(const al::SensorMsg*);
bool isMsgHammerAttackDown(const al::SensorMsg*);
bool isMsgHammerAttackSide(const al::SensorMsg*);
bool isMsgHammerAttackSideCollide(const al::SensorMsg*);
bool isMsgHammerBrosHammerEnemyAttack(const al::SensorMsg*);
bool isMsgHammerBrosHammerHackAttack(const al::SensorMsg*);
bool isMsgHammerBrosHammerSearch(const al::SensorMsg*);
bool isMsgHipDropTransformReverse(const al::SensorMsg*);
bool isMsgHipDropTransformTransform(const al::SensorMsg*);
bool isMsgHipDropTransformingUp(const al::SensorMsg*);
bool isMsgHipDropTransformingDown(const al::SensorMsg*);
bool isMsgHipDropTransformingFinish(const al::SensorMsg*);
bool isMsgHitGrowFlowerPot(const al::SensorMsg*);
bool isMsgHitGrowPlantPot(const al::SensorMsg*);
bool isMsgHosuiAttack(const al::SensorMsg*);
bool isMsgHosuiAttackCollide(const al::SensorMsg*);
bool isMsgHosuiAttackNoEffect(const al::SensorMsg*);
bool isMsgHosuiAttackStrong(const al::SensorMsg*);
bool isMsgHosuiTouch(const al::SensorMsg*);
bool isMsgHosuiTrample(const al::SensorMsg*);
bool isMsgHosuiTrampleReflect(const al::SensorMsg*);
bool isMsgHosuiTrampleReflectHigh(const al::SensorMsg*);
bool isMsgIgnoreTouchTarget(const al::SensorMsg*);
bool isMsgIgnorePushMotorcycle(const al::SensorMsg*);
bool isMsgIcicleAttack(const al::SensorMsg*);
bool isMsgIgnoreMirrorWarp(const al::SensorMsg*);
bool isMsgIgnoredByRunawayNpc(const al::SensorMsg*);
bool isMsgImplantGrowFlowerSeed(const al::SensorMsg*);
bool isMsgInitTouchTargetInfo(const al::SensorMsg*);
bool isMsgItemAmiiboKoopa(const al::SensorMsg*);
bool isMsgIsExistPukupuku(const al::SensorMsg*);
bool isMsgJangoAttack(const al::SensorMsg*);
bool isMsgJangoRemoveCap(const al::SensorMsg*);
bool isMsgKakkuKick(const al::SensorMsg*);
bool isMsgKoopaBindStart(const al::SensorMsg*);
bool isMsgKoopaCapPlayerFocusTarget(const al::SensorMsg*);
bool isMsgKoopaCapPunchFinishL(const al::SensorMsg*);
bool isMsgKoopaCapPunchFinishR(const al::SensorMsg*);
bool isMsgKoopaCapPunchInvincibleL(const al::SensorMsg*);
bool isMsgKoopaCapPunchInvincibleR(const al::SensorMsg*);
bool isMsgKoopaCapPunchKnockBackL(const al::SensorMsg*);
bool isMsgKoopaCapPunchKnockBackR(const al::SensorMsg*);
bool isMsgKoopaCapPunchL(const al::SensorMsg*);
bool isMsgKoopaCapPunchR(const al::SensorMsg*);
bool isMsgKoopaCapSpinAttack(const al::SensorMsg*);
bool isMsgKoopaCatchKoopaCap(const al::SensorMsg*);
bool isMsgKoopaDashPunchAttack(const al::SensorMsg*);
bool isMsgKoopaFire2D(const al::SensorMsg*);
bool isMsgKoopaFireBallAttack(const al::SensorMsg*);
bool isMsgKoopaHackDamage(const al::SensorMsg*);
bool isMsgKoopaHackPunch(const al::SensorMsg*);
bool isMsgKoopaHackPunchCollide(const al::SensorMsg*);
bool isMsgKoopaHackTrample(const al::SensorMsg*);
bool isMsgKoopaInvalidHackPunchFaceToCollision(const al::SensorMsg*);
bool isMsgKoopaRingBeamInvalidTouch(const al::SensorMsg*);
bool isMsgKoopaTailAttack(const al::SensorMsg*);
bool isMsgKoopaTouchFloor(const al::SensorMsg*);
bool isMsgKouraAttack2D(const al::SensorMsg*);
bool isMsgKouraItemGet2D(const al::SensorMsg*);
bool isMsgKuribo2DTouch(const al::SensorMsg*);
bool isMsgKuriboCollisionDamage(const al::SensorMsg*);
bool isMsgKuriboCollisionKill(const al::SensorMsg*);
bool isMsgKuriboFlick(const al::SensorMsg*);
bool isMsgKuriboGirlAttack(const al::SensorMsg*);
bool isMsgKuriboGirlLove(const al::SensorMsg*);
bool isMsgKuriboTop(const al::SensorMsg*);
bool isMsgKuriboTowerNum(const al::SensorMsg*);
bool isMsgLaunchBlow(const al::SensorMsg*);
bool isMsgLineDancerLink(const al::SensorMsg*);
bool isMsgLongPushSensorHit(const al::SensorMsg*);
bool isMsgLongPushBoxHit(const al::SensorMsg*);
bool isMsgMagnetBulletAttack(const al::SensorMsg*);
bool isMsgMeganeAttack(const al::SensorMsg*);
bool isMsgMeganeHackTrample(const al::SensorMsg*);
bool isMsgMofumofuBodyChainExplode(const al::SensorMsg*);
bool isMsgMofumofuBulletUnexplosion(const al::SensorMsg*);
bool isMsgMoonBasementAttackMeteor(const al::SensorMsg*);
bool isMsgMoonBasementBreakShockwaveMeteor(const al::SensorMsg*);
bool isMsgMoonBasementRockSyncClippingRegist(const al::SensorMsg*);
bool isMsgMoonBasementRockSyncClippingInvalidate(const al::SensorMsg*);
bool isMsgMoonBasementRockSyncClippingValidate(const al::SensorMsg*);
bool isMsgMoonBasementRockThroughCollision(const al::SensorMsg*);
bool isMsgMorningStarWarpEnd(const al::SensorMsg*);
bool isMsgMorningStarWarpStart(const al::SensorMsg*);
bool isMsgMotorcycleAttack(const al::SensorMsg*);
bool isMsgMotorcycleCollideParkingLot(const al::SensorMsg*);
bool isMsgMotorcycleDashAttack(const al::SensorMsg*);
bool isMsgMotorcycleDashCollide(const al::SensorMsg*);
bool isMsgCactusNeedleAttack(const al::SensorMsg*);
bool isMsgCactusNeedleAttackStrong(const al::SensorMsg*);
bool isMsgNoLimitTouchJump(const al::SensorMsg*);
bool isMsgNoticePlayerDamage(const al::SensorMsg*);
bool isMsgNpcScareByEnemy(const al::SensorMsg*);
bool isMsgVolleyballNpcScareByEnemy(const al::SensorMsg*);
bool isMsgObjSnapForce(const al::SensorMsg*);
bool isMsgPackunEatCancel(const al::SensorMsg*);
bool isMsgPackunEatEnd(const al::SensorMsg*);
bool isMsgPackunEatStart(const al::SensorMsg*);
bool isMsgPackunEatStartFollow(const al::SensorMsg*);
bool isMsgPaint(const al::SensorMsg*);
bool isMsgPaintTexture(const al::SensorMsg*);
bool isMsgCheckPaintClear(const al::SensorMsg*);
bool isMsgCheckPaintAlpha(const al::SensorMsg*);
bool isMsgPartyPopperSoundAttack(const al::SensorMsg*);
bool isMsgPechoSpot(const al::SensorMsg*);
bool isMsgPlayerBallToss(const al::SensorMsg*);
bool isMsgPlayerCarryCameraSubjectiveStart(const al::SensorMsg*);
bool isMsgPlayerCarryCameraSubjectiveEnd(const al::SensorMsg*);
bool isMsgPlayerCarryShineGetStart(const al::SensorMsg*);
bool isMsgPlayerCarryShineGetEnd(const al::SensorMsg*);
bool isMsgPlayerCapCatch(const al::SensorMsg*);
bool isMsgPlayerCapHipDrop(const al::SensorMsg*);
bool isMsgPlayerCapPush(const al::SensorMsg*);
bool isMsgPlayerCapRecovery(const al::SensorMsg*);
bool isMsgPlayerCapTouchJump(const al::SensorMsg*);
bool isMsgPlayerCapTrample(const al::SensorMsg*);
bool isMsgPlayerCoinDashGet(const al::SensorMsg*);
bool isMsgPlayerEyePriorityTarget(const al::SensorMsg*);
bool isMsgPlayerDisregardHomingAttack(const al::SensorMsg*);
bool isMsgPlayerDisregardTargetMarker(const al::SensorMsg*);
bool isMsgPlayerEquipKoopaCap(const al::SensorMsg*);
bool isMsgPlayerFireBallAttack2D(const al::SensorMsg*);
bool isMsgPlayerFireBallAttack3D(const al::SensorMsg*);
bool isMsgPlayerHipDropDemoTrigger(const al::SensorMsg*);
bool isMsgPlayerHipDropHipDropSwitch(const al::SensorMsg*);
bool isMsgPlayerItemGet2D(const al::SensorMsg*);
bool isMsgPlayerJumpTakeOffFloor(const al::SensorMsg*);
bool isMsgPlayerObjectWallHit(const al::SensorMsg*);
bool isMsgPlayerObjLeapFrog(const al::SensorMsg*);
bool isMsgPlayerPenguinAttack(const al::SensorMsg*);
bool isMsgPlayerPenguinAttackReflect(const al::SensorMsg*);
bool isMsgPlayerPoleClimbKeep(const al::SensorMsg*);
bool isMsgPlayerPoleClimbReaction(const al::SensorMsg*);
bool isMsgPlayerRabbitGet(const al::SensorMsg*);
bool isMsgPlayerRollingObjHit(const al::SensorMsg*);
bool isMsgPlayerRollingWallHitDown(const al::SensorMsg*);
bool isMsgPlayerRollingWallHitMove(const al::SensorMsg*);
bool isMsgPlayerStartGrabCeil(const al::SensorMsg*);
bool isMsgPlayerStartWallJump(const al::SensorMsg*);
bool isMsgPlayerEndGrabCeil(const al::SensorMsg*);
bool isMsgPlayerSwordAttack(const al::SensorMsg*);
bool isMsgPlayerTouchFloorJumpCode(const al::SensorMsg*);
bool isMsgPlayerTrample2D(const al::SensorMsg*);
bool isMsgPlayerUpperPunch2D(const al::SensorMsg*);
bool isMsgPlayerObjUpperPunch2D(const al::SensorMsg*);
bool isMsgPropellerAttack(const al::SensorMsg*);
bool isMsgPukupukuDash(const al::SensorMsg*);
bool isMsgPukupukuKiss(const al::SensorMsg*);
bool isMsgPukupukuRollingAttack(const al::SensorMsg*);
bool isMsgPunchMachinePunchHook(const al::SensorMsg*);
bool isMsgPunchMachinePunchStraight(const al::SensorMsg*);
bool isMsgPunchMachinePunchUpper(const al::SensorMsg*);
bool isMsgPush2D(const al::SensorMsg*);
bool isMsgPushToFish(const al::SensorMsg*);
bool isMsgPushToMotorcycle(const al::SensorMsg*);
bool isMsgPushToPlayer(const al::SensorMsg*);
bool isMsgRadishAttack(const al::SensorMsg*);
bool isMsgRadishReflect(const al::SensorMsg*);
bool isMsgRaceStart(const al::SensorMsg*);
bool isMsgRaceStop(const al::SensorMsg*);
bool isMsgRaceWait(const al::SensorMsg*);
bool isMsgRequestChangeFireFlower(const al::SensorMsg*);
bool isMsgRequestChangeKinokoSuper(const al::SensorMsg*);
bool isMsgRequestPlayerJumpBreakFloor(const al::SensorMsg*);
bool isMsgRequestPlayerJump(const al::SensorMsg*);
bool isMsgRequestPlayerTrampleJump(const al::SensorMsg*);
bool isMsgRequestPlayerSpinJump(const al::SensorMsg*);
bool isMsgRequestSphinxJump(const al::SensorMsg*);
bool isMsgRideOnEnd(const al::SensorMsg*);
bool isMsgRideOnRelease(const al::SensorMsg*);
bool isMsgRideOnStart(const al::SensorMsg*);
bool isMsgRocketFlowerExtension(const al::SensorMsg*);
bool isMsgSandSharkAttack(const al::SensorMsg*);
bool isMsgSeedAttack(const al::SensorMsg*);
bool isMsgSeedAttackBig(const al::SensorMsg*);
bool isMsgSeedAttackHold(const al::SensorMsg*);
bool isMsgSeedItemGet(const al::SensorMsg*);
bool isMsgSeedReflect(const al::SensorMsg*);
bool isMsgSeedTouch(const al::SensorMsg*);
bool isMsgSenobiCancelStretch(const al::SensorMsg*);
bool isMsgSenobiPunchBlockTransparent(const al::SensorMsg*);
bool isMsgSenobiPartsMove(const al::SensorMsg*);
bool isMsgSenobiTrample(const al::SensorMsg*);
bool isMsgShibakenApproach(const al::SensorMsg*);
bool isMsgShibakenKick(const al::SensorMsg*);
bool isMsgSkaterAttack(const al::SensorMsg*);
bool isMsgSpherePush(const al::SensorMsg*);
bool isMsgSphinxJumpAttack(const al::SensorMsg*);
bool isMsgSphinxQuizRouteKill(const al::SensorMsg*);
bool isMsgSphinxRideAttack(const al::SensorMsg*);
bool isMsgSphinxRideAttackReflect(const al::SensorMsg*);
bool isMsgSphinxRideAttackTouchThrough(const al::SensorMsg*);
bool isMsgSphinxRideAttackTouch(const al::SensorMsg*);
bool isMsgStampTo2D(const al::SensorMsg*);
bool isMsgStartHack(const al::SensorMsg*);
bool isMsgStartInSaucePan(const al::SensorMsg*);
bool isMsgStatueDrop(const al::SensorMsg*);
bool isMsgStatueTrampleReflect(const al::SensorMsg*);
bool isMsgStatuePush(const al::SensorMsg*);
bool isMsgStatueSnap(const al::SensorMsg*);
bool isMsgSunshineAttack(const al::SensorMsg*);
bool isMsgTankBullet(const al::SensorMsg*);
bool isMsgTankBulletNoReaction(const al::SensorMsg*);
bool isMsgTankExplosion(const al::SensorMsg*);
bool isMsgTankHackTrample(const al::SensorMsg*);
bool isMsgTankKickHack(const al::SensorMsg*);
bool isMsgTankKickEnemy(const al::SensorMsg*);
bool isMsgTankLookOn(const al::SensorMsg*);
bool isMsgTestPunch(const al::SensorMsg*);
bool isMsgTestPunchStrong(const al::SensorMsg*);
bool isMsgTimerAthleticDemoStart(const al::SensorMsg*);
bool isMsgTouchDoorDrumn(const al::SensorMsg*);
bool isMsgTouchFireDrum2D(const al::SensorMsg*);
bool isMsgTrashBoxIn(const al::SensorMsg*);
bool isMsgTRexAttack(const al::SensorMsg*);
bool isMsgTRexAttackCollideAll(const al::SensorMsg*);
bool isMsgTRexAttackCollideBody(const al::SensorMsg*);
bool isMsgTRexAttackCollideHead(const al::SensorMsg*);
bool isMsgTRexDashAttack(const al::SensorMsg*);
bool isMsgTRexScrollPartsBreakWith(const al::SensorMsg*);
bool isMsgTsukkunForceCancelCollide(const al::SensorMsg*);
bool isMsgTsukkunHoldCollide(const al::SensorMsg*);
bool isMsgTsukkunThroughCollide(const al::SensorMsg*);
bool isMsgTsukkunThrustAll(const al::SensorMsg*);
bool isMsgTsukkunThrust(const al::SensorMsg*, bool*);
bool isMsgTsukkunThrustCollide(const al::SensorMsg*, bool*);
bool isMsgTsukkunNoTrace(const al::SensorMsg*);
bool isMsgTsukkunThrustHole(const al::SensorMsg*);
bool isMsgUtsuboAttack(const al::SensorMsg*);
bool isMsgWanderBossCameraRange(const al::SensorMsg*);
bool isMsgWanwanEnemyAttack(const al::SensorMsg*);
bool isMsgWanwanBlockAttack(const al::SensorMsg*);
bool isMsgWanwanHoleIn(const al::SensorMsg*);
bool isMsgWaterRoadIn(const al::SensorMsg*);
bool isMsgWaterRoadNear(const al::SensorMsg*);
bool isMsgWanwanPush(const al::SensorMsg*);
bool isMsgWanwanReboundAttack(const al::SensorMsg*);
bool isMsgWeaponItemGet(const al::SensorMsg*);
bool isMsgWhipAttack(const al::SensorMsg*);
bool isMsgWhipBind(const al::SensorMsg*);
bool isMsgWhipHold(const al::SensorMsg*);
bool isMsgWhipThrow(const al::SensorMsg*);
bool isMsgYokinBallAttack(const al::SensorMsg*);
bool isMsgYoshiDirectEat(const al::SensorMsg*);
bool isMsgYoshiTongueAttack(const al::SensorMsg*);
bool isMsgYoshiTongueEatBind(const al::SensorMsg*);
bool isMsgYoshiTongueEatBindCancel(const al::SensorMsg*);
bool isMsgYoshiTongueEatBindFinish(const al::SensorMsg*);
bool isMsgYoshiTongueEatHomingTarget(const al::SensorMsg*);
bool isMsgYukimaruPush(const al::SensorMsg*);
bool isMsgKillerAttackNoExplode(const al::SensorMsg*);
bool isMsgKillerMagnumAttack(const al::SensorMsg*);
bool isMsgKillerMagnumHackAttack(const al::SensorMsg*);
bool isMsgGabuzouAttack(const al::SensorMsg*);
bool isMsgStackerRollingAttack(const al::SensorMsg*);
bool isMsgStackerCapBoostAttack(const al::SensorMsg*);
bool isMsgIgnoreIgnitionBomb(const al::SensorMsg*);
bool isMsgExplosionReflectBomb(const al::SensorMsg*);
bool isMsgGolemStampPress(const al::SensorMsg*);
bool isMsgTsukkunThrustSpin(const al::SensorMsg*, bool*);
bool isMsgTsukkunThrustReflect(const al::SensorMsg*, bool*);
bool isMsgTsukkunThrustHitReflectCollide(const al::SensorMsg*, bool*);
bool isMsgTsukkunThrustReflectCollide(const al::SensorMsg*, bool*);
bool isMsgSwitchOnWithSaveRequest(const al::SensorMsg*, struct SaveObjInfo**);
bool isMsgNpcCapReactionAll(const al::SensorMsg*);
bool isMsgHackNpcCapReactionAll(const al::SensorMsg*);
bool isMsgPlayerAndCapObjHipDropReflectAll(const al::SensorMsg*);
bool isMsgKoopaCapPunchAll(const al::SensorMsg*);
bool isMsgKoopaCapPunchInvincibleAll(const al::SensorMsg*);
bool isMsgKoopaCapPunchFinishAll(const al::SensorMsg*);
bool isMsgItemGet(const al::SensorMsg*);
bool isMsgItemGetByWeapon(const al::SensorMsg*);
bool isMsgItemGet2D(const al::SensorMsg*);
bool isMsgBlockUpperPunch2D(const al::SensorMsg*);
bool isMsgItemGetAll(const al::SensorMsg*);
bool isMsgShineGet(const al::SensorMsg*);
bool isMsgShineGet2D(const al::SensorMsg*);
bool isMsgShineReaction(const al::SensorMsg*);
bool isMsgKillByShineGet(const al::SensorMsg*);
bool isMsgKillByHomeDemo(const al::SensorMsg*);
bool isMsgEndHomeDemo(const al::SensorMsg*);
bool isMsgBreakBySword(const al::SensorMsg*);
bool isMsgPressDown(const al::SensorMsg*);
bool isMsgPlayerAndCapObjHipDropAll(const al::SensorMsg*);
bool isMsgAttackDirect(const al::SensorMsg*);
bool isMsgBlowDown(const al::SensorMsg*);
bool isMsgTrampleReflectAll(const al::SensorMsg*);
bool isMsgThrowObjHit(const al::SensorMsg*);
bool isMsgThrowObjHitReflect(const al::SensorMsg*);
bool isMsgPlayerAndCapHipDropAll(const al::SensorMsg*);
bool isMsgUpperPunchAll(const al::SensorMsg*);
bool isMsgBlockReaction2D(const al::SensorMsg*);
bool isMsgBlockReaction3D(const al::SensorMsg*);
bool isMsgBlockReactionAll(const al::SensorMsg*);
bool isMsgBreakFrailBox(const al::SensorMsg*);
bool isMsgDamageFrailBox(const al::SensorMsg*);
bool isMsgChorobonReaction(const al::SensorMsg*);
bool isMsgBreakSignBoard(const al::SensorMsg*);
bool isMsgBreakCollapseSandHill(const al::SensorMsg*);
bool isMsgPlayerDamage(const al::SensorMsg*);
bool isMsgPlayerDamage2D(const al::SensorMsg*);
bool isMsgPlayerDamageBlowDown(const al::SensorMsg*);
bool isMsgPlayerJumpRequestAll(const al::SensorMsg*);
bool isMsgDashPanel(const al::SensorMsg*, int*);
bool isMsgNetworkShootingShot(const al::SensorMsg*, int);
bool isMsgNetworkShootingChargeShot(const al::SensorMsg*, int);
bool isMsgRaceReturnToCourse(const al::SensorMsg*, sead::Vector3f*, sead::Vector3f*);
bool isMsgTrampolineCrackJump(float*, float*, const al::SensorMsg*);
bool isMsgGotogotonOn(const al::SensorMsg*);
bool isMsgGotogotonGoalExist(const al::SensorMsg*);
bool isMsgBossMagmaCatchPlayer(const al::SensorMsg*);
bool isMsgBossMagmaReleasePlayer(const al::SensorMsg*);
bool isMsgBossMagmaDeadDemoStart(const al::SensorMsg*);
bool isMsgBossMagmaDeadDemoEnd(const al::SensorMsg*);
bool isMsgBossMagmaQueryToBubble(const al::SensorMsg*);
bool isMsgMofumofuReflectAll(const al::SensorMsg*);
bool isMsgCheckFishingTarget(const al::SensorMsg*);
bool isMsgPlayerLookAtPosition(const al::SensorMsg*);
bool isMsgTargetMarkerPosition(const al::SensorMsg*);
bool isMsgSandGeyserRaise(const al::SensorMsg*);
bool isMsgInitCapTarget(const al::SensorMsg*);
bool isMsgTransferHack(const al::SensorMsg*);
bool isMsgRequestTransferHack(const al::SensorMsg*);
bool isMsgInitHack(const al::SensorMsg*);
bool isMsgEndHack(struct HackEndParam const**, const al::SensorMsg*);
bool isMsgHackDirectStageInit(struct IUsePlayerHack**, const al::SensorMsg*);
bool isMsgKillByBossBattleDemo(const al::SensorMsg*);
bool isMsgKillByHackFirstDemo(const al::SensorMsg*);
bool isMsgKillByMoonRockDemo(const al::SensorMsg*);
bool isMsgKillBySwitchTimer(const al::SensorMsg*);

bool setMsgYoshiTongueEatBindRadiusAndOffset(const al::SensorMsg*, float, float);
bool setMsgYoshiTongueEatBindScale(const al::SensorMsg*, float);
bool setMsgPlayerLookAtPosition(const al::SensorMsg*, const sead::Vector3f&);
bool setMsgTargetMarkerPosition(const al::SensorMsg*, const sead::Vector3f&);

bool requestHitReactionToAttacker(const al::SensorMsg*, const al::HitSensor*, const al::HitSensor*);

bool sendMsgHackerNoReaction(const IUsePlayerHack*, al::HitSensor*, al::HitSensor*);
bool sendMsgHackerNoReactionWithoutShine(const IUsePlayerHack*, al::HitSensor*, al::HitSensor*);
bool sendMsgBreakFloorToPlayer(const al::LiveActor*);
bool sendMsgAckCheckpoint(al::HitSensor*, al::HitSensor*);
bool sendMsgAckGetShine(al::HitSensor*, al::HitSensor*);
bool sendMsgAckLifeUp(al::HitSensor*, al::HitSensor*);
bool sendMsgAckLifeMaxUp(al::HitSensor*, al::HitSensor*);
bool sendMsgAskRailCollision(al::HitSensor*, al::HitSensor*);
bool sendMsgBreakPartsBreak(al::HitSensor*, al::HitSensor*);
bool sendMsgBirdFlyAway(al::HitSensor*, al::HitSensor*);
bool sendMsgCameraAngleElevationResetFast(al::HitSensor*, al::HitSensor*);
bool sendMsgChorobonAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgConductLightning(al::HitSensor*, al::HitSensor*);
bool sendMsgDamageBallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgDamageBallBodyAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgDonsukeAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgDonsukeGroundAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgDonsukePush(al::HitSensor*, al::HitSensor*);
bool sendMsgDragonAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgEatExplosion(al::HitSensor*, al::HitSensor*);
bool sendMsgElectricWireNoLimitDistance(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttack2D(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttack3D(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackDash(al::HitSensor*, al::HitSensor*);
bool sendMsgHackAttackFire(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackFireCollision(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackPoison(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackTRex(al::HitSensor*, al::HitSensor*);
bool sendMsgHackAttackPoison(al::HitSensor*, al::HitSensor*);
bool sendMsgConfirmPaintObj(al::HitSensor*, al::HitSensor*);
bool sendMsgConfirmPaintObjForSeed(al::HitSensor*, al::HitSensor*);
bool sendMsgPaintAttackPoison(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyKick(al::HitSensor*, al::HitSensor*);
bool sendMsgRabbitKick(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingCancel(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingFishApproach(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingFishFloatTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingLineTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingStart(al::HitSensor*, al::HitSensor*);
bool sendMsgFishingUpImmediatelyPrepare(al::HitSensor*, al::HitSensor*);
bool sendMsgFireBrosFireBallCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgFireSwitchFire(al::HitSensor*, al::HitSensor*);
bool sendMsgFrogHackTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgGhostRecordStart(al::HitSensor*, al::HitSensor*);
bool sendMsgGhostRecordEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgGhostPlay(al::HitSensor*, al::HitSensor*);
bool sendMsgGhostStop(al::HitSensor*, al::HitSensor*);
bool sendMsgGiantWanderBossAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgGiantWanderBossBulletAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgGiantWanderBossBulletPush(al::HitSensor*, al::HitSensor*);
bool sendMsgGhostReverse(al::HitSensor*, al::HitSensor*);
bool sendMsgGhostCancel(al::HitSensor*, al::HitSensor*);
bool sendMsgGrowFlowerSeedDisablePush(al::HitSensor*, al::HitSensor*);
bool sendMsgGrowFlowerSeedNear(al::HitSensor*, al::HitSensor*);
bool sendMsgGrowPlantPush(al::HitSensor*, al::HitSensor*);
bool sendMsgGrowerAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgGrowerWallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgGunetterAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgGunetterBodyTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgHammerAttackDown(al::HitSensor*, al::HitSensor*);
bool sendMsgHammerAttackSide(al::HitSensor*, al::HitSensor*);
bool sendMsgHammerAttackSideCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgItemAmiiboKoopa(al::HitSensor*, al::HitSensor*);
bool sendMsgIsExistPukupuku(al::HitSensor*, al::HitSensor*);
bool sendMsgJangoAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgJangoRemoveCap(al::HitSensor*, al::HitSensor*);
bool sendMsgKakkuKick(al::HitSensor*, al::HitSensor*);
bool sendMsgKillByBossBattleDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgKillByHackFirstDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgKillByHomeDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgEndHomeDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgKillByMoonRockDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgKillByShineGet(al::HitSensor*, al::HitSensor*);
bool sendMsgKillBySwitchTimer(al::LiveActor*);
bool sendMsgKoopaBindStart(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPlayerFocusTarget(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchFinishL(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchFinishR(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchInvincibleL(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchInvincibleR(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchKnockBackL(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchKnockBackR(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchL(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapPunchR(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCapSpinAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaCatchKoopaCap(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaDashPunchAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaFire2D(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaFireBallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaHackDamage(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaHackPunch(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaHackPunchCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaHackTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaInvalidHackPunchFaceToCollision(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaRingBeamInvalidTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaTailAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKoopaTouchFloor(al::HitSensor*, al::HitSensor*);
bool sendMsgKouraAttack2D(al::HitSensor*, al::HitSensor*);
bool sendMsgKouraItemGet2D(al::HitSensor*, al::HitSensor*);
bool sendMsgLaunchBlow(al::HitSensor*, al::HitSensor*);
bool sendMsgMeganeAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgMeganeHackTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgMofumofuBulletUnexplosion(al::HitSensor*, al::HitSensor*);
bool sendMsgMoonBasementAttackMeteor(al::HitSensor*, al::HitSensor*);
bool sendMsgMoonBasementBreakShockwaveMeteor(al::HitSensor*, al::HitSensor*);
bool sendMsgMoonBasementRockSyncClippingRegist(al::HitSensor*, al::HitSensor*);
bool sendMsgMoonBasementRockSyncClippingInvalidate(al::HitSensor*, al::HitSensor*);
bool sendMsgMoonBasementRockSyncClippingValidate(al::HitSensor*, al::HitSensor*);
bool sendMsgAttachCactusNeedle(al::HitSensor*, al::HitSensor*);
bool sendMsgCactusNeedleAttack(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgCactusNeedleAttackStrong(al::HitSensor*, al::HitSensor*, al::ComboCounter*);
bool sendMsgPlayerBallToss(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryCameraSubjectiveStart(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryCameraSubjectiveEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryShineGetStart(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCarryShineGetEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCapCatch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCapHipDrop(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCapPush(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCapRecovery(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCapTouchJump(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCapTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerCoinDashGet(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerEyePriorityTarget(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerDisregardHomingAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerDisregardTargetMarker(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerEquipKoopaCap(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerFireBallAttack2D(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerFireBallAttack3D(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerHipDropDemoTrigger(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerHipDropHipDropSwitch(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerItemGet2D(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerJumpTakeOffFloor(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerObjectWallHit(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerObjLeapFrog(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerPenguinAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerPenguinAttackReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerPoleClimbKeep(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerPoleClimbReaction(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRabbitGet(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRollingObjHit(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRollingWallHitDown(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerRollingWallHitMove(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerStartGrabCeil(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerStartWallJump(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerEndGrabCeil(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerSwordAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerTouchFloorJumpCode(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerTrample2D(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerUpperPunch2D(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerObjUpperPunch2D(al::HitSensor*, al::HitSensor*);
bool sendMsgPukupukuDash(al::HitSensor*, al::HitSensor*);
bool sendMsgPukupukuKiss(al::HitSensor*, al::HitSensor*);
bool sendMsgPukupukuRollingAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgPush2D(al::HitSensor*, al::HitSensor*);
bool sendMsgPushToFish(al::HitSensor*, al::HitSensor*);
bool sendMsgPushToMotorcycle(al::HitSensor*, al::HitSensor*);
bool sendMsgPushToPlayer(al::HitSensor*, al::HitSensor*);
bool sendMsgRadishAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgRadishReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgRequestChangeKinokoSuper(al::HitSensor*, al::HitSensor*);
bool sendMsgRequestChangeFireFlower(al::HitSensor*, al::HitSensor*);
bool sendMsgRequestPlayerSandMoon(al::HitSensor*, al::HitSensor*);
bool sendMsgRequestPlayerSnow(al::HitSensor*, al::HitSensor*);
bool sendMsgRequestPlayerWet(al::HitSensor*, al::HitSensor*);
bool sendMsgStartHack(al::HitSensor*, al::HitSensor*);
bool sendMsgSunshineAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgCancelHack(al::HitSensor*, al::HitSensor*);
bool sendMsgCancelHackArea(al::HitSensor*, al::HitSensor*);
bool sendMsgCancelHackByDokan(al::HitSensor*, al::HitSensor*);
bool sendMsgPackunEatStart(al::HitSensor*, al::HitSensor*);
bool sendMsgHackAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgHackAttackKick(al::HitSensor*, al::HitSensor*);
bool sendMsgHackAttackMapObj(al::HitSensor*, al::HitSensor*);
bool sendMsgHackDeathAreaSelfCheck(al::HitSensor*, al::HitSensor*);
bool sendMsgHackDemoEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgHackDemoStart(al::HitSensor*, al::HitSensor*);
bool sendMsgHackInvalidEscape(al::HitSensor*, al::HitSensor*);
bool sendMsgHackInvalidEscapeNoReaction(al::HitSensor*, al::HitSensor*);
bool sendMsgHackMarioCheckpointFlagWarp(al::HitSensor*, al::HitSensor*);
bool sendMsgHackMarioDead(al::HitSensor*, al::HitSensor*);
bool sendMsgHackMarioDemo(al::HitSensor*, al::HitSensor*);
bool sendMsgHackMarioInWater(al::HitSensor*, al::HitSensor*);
bool sendMsgHackMoveRockForestPush(al::HitSensor*, al::HitSensor*);
bool sendMsgHackSelfCeilingCheckMiss(al::HitSensor*, al::HitSensor*);
bool sendMsgHackSyncDamageVisibility(al::HitSensor*, al::HitSensor*);
bool sendMsgWeaponItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgCapAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgCapAttackCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgCapAttackStayRolling(al::HitSensor*, al::HitSensor*);
bool sendMsgCapAttackStayRollingCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgCapAttackRailMove(al::HitSensor*, al::HitSensor*);
bool sendMsgCapGiantAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgCapReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgCapReflectCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgCapStartLockOn(al::HitSensor*, al::HitSensor*);
bool sendMsgCapKeepLockOn(al::HitSensor*, al::HitSensor*);
bool sendMsgCapCancelLockOn(al::HitSensor*, al::HitSensor*);
bool sendMsgCapHipDrop(al::HitSensor*, al::HitSensor*);
bool sendMsgCapObjHipDrop(al::HitSensor*, al::HitSensor*);
bool sendMsgCapObjHipDropReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgCapIgnoreCancelLockOn(al::HitSensor*, al::HitSensor*);
bool sendMsgCapIgnoreCancelMissReaction(al::HitSensor*, al::HitSensor*);
bool sendMsgCapIgnoreCollisionCheck(al::HitSensor*, al::HitSensor*);
bool sendMsgCapItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgCapTrampolineAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgCatchBombThrough(al::HitSensor*, al::HitSensor*);
bool sendMsgCheckCarObstacle(al::HitSensor*, al::HitSensor*);
bool sendMsgCheckIsCardboardBox(al::HitSensor*, al::HitSensor*);
bool sendMsgBullHackAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgBullEnemyAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyAttackStrong(al::HitSensor*, al::HitSensor*);
bool sendMsgEnemyObjBreak(al::HitSensor*, al::HitSensor*);
bool sendMsgWhipAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgNoLimitTouchJump(al::HitSensor*, al::HitSensor*);
bool sendMsgNoticePlayerDamage(al::HitSensor*, al::HitSensor*);
bool sendMsgStatueDrop(al::HitSensor*, al::HitSensor*);
bool sendMsgStatueTrampleReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgStatuePush(al::HitSensor*, al::HitSensor*);
bool sendMsgStatueSnap(al::HitSensor*, al::HitSensor*);
bool sendMsgHitGrowFlowerPot(al::HitSensor*, al::HitSensor*);
bool sendMsgHitGrowPlantPot(al::HitSensor*, al::HitSensor*);
bool sendMsgImplantGrowFlowerSeed(al::HitSensor*, al::HitSensor*);
bool sendMsgIcicleAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgIgnoreMirrorWarp(al::HitSensor*, al::HitSensor*);
bool sendMsgIgnoredByRunawayNpc(al::HitSensor*, al::HitSensor*);
bool sendMsgIgnorePushMotorcycle(al::HitSensor*, al::HitSensor*);
bool sendMsgSandSharkAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgSeedAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgSeedAttackBig(al::HitSensor*, al::HitSensor*);
bool sendMsgSeedAttackHold(al::HitSensor*, al::HitSensor*);
bool sendMsgSeedItemGet(al::HitSensor*, al::HitSensor*);
bool sendMsgSeedReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgSenobiTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgSenobiCancelStretch(al::HitSensor*, al::HitSensor*);
bool sendMsgSenobiPunchBlockTransparent(al::HitSensor*, al::HitSensor*);
bool sendMsgShibakenApproach(al::HitSensor*, al::HitSensor*);
bool sendMsgShibakenKick(al::HitSensor*, al::HitSensor*);
bool sendMsgHackUpperPunch(al::HitSensor*, al::HitSensor*);
bool sendMsgHackObjUpperPunch(al::HitSensor*, al::HitSensor*);
bool sendMsgShineGet(al::HitSensor*, al::HitSensor*);
bool sendMsgShineGet2D(al::HitSensor*, al::HitSensor*);
bool sendMsgSpherePush(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, float);
bool sendMsgSphinxJumpAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgSphinxQuizRouteKill(al::HitSensor*, al::HitSensor*);
bool sendMsgSphinxRideAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgSphinxRideAttackReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgPechoSpot(al::HitSensor*, al::HitSensor*);
bool sendMsgBelowObjBroken(al::HitSensor*, al::HitSensor*);
bool sendMsgBindCollidedGround(al::HitSensor*, al::HitSensor*);
bool sendMsgBindKeepDemoStart(al::HitSensor*, al::HitSensor*);
bool sendMsgBindKeepDemoExecute(al::HitSensor*, al::HitSensor*);
bool sendMsgBindKeepDemoEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgBindRecoveryLife(al::HitSensor*, al::HitSensor*);
bool sendMsgMayorItemReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgMayorItemCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgBlowObjAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgBlowObjAttackReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgConfirmFrailBox(al::HitSensor*, al::HitSensor*);
bool sendMsgConfirmBrokenFrailBox(al::HitSensor*, al::HitSensor*);
bool sendMsgTankLookOn(al::HitSensor*, al::HitSensor*);
bool sendMsgTankKickHack(al::HitSensor*, al::HitSensor*);
bool sendMsgTankKickEnemy(al::HitSensor*, al::HitSensor*);
bool sendMsgTankBullet(al::HitSensor*, al::HitSensor*);
bool sendMsgTankBulletNoReaction(al::HitSensor*, al::HitSensor*);
bool sendMsgTimerAthleticDemoStart(al::LiveActor*);
bool sendMsgRideOnStart(al::HitSensor*, al::HitSensor*);
bool sendMsgRideOnEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgRideOnRelease(al::HitSensor*, al::HitSensor*);
bool sendMsgHipDropTransformTransform(al::HitSensor*, al::HitSensor*);
bool sendMsgHipDropTransformReverse(al::HitSensor*, al::HitSensor*);
bool sendMsgHipDropTransformingUp(al::HitSensor*, al::HitSensor*);
bool sendMsgHipDropTransformingDown(al::HitSensor*, al::HitSensor*);
bool sendMsgHipDropTransformingFinish(al::HitSensor*, al::HitSensor*);
bool sendMsgClearFire(al::HitSensor*, al::HitSensor*);
bool sendMsgCollectAnimalTouchCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgBossKnuckleCounter(al::HitSensor*, al::HitSensor*);
bool sendMsgBossKnuckleFallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgBossKnuckleHackAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgBossKnuckleKillerAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgBossKnuckleIceConflict(al::HitSensor*, al::HitSensor*);
bool sendMsgBossKnuckleIceFallToMummy(al::HitSensor*, al::HitSensor*);
bool sendMsgSkaterAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgEnableInSaucePan(al::HitSensor*, al::HitSensor*);
bool sendMsgEnableMapCheckPointWarp(al::HitSensor*, al::HitSensor*);
bool sendMsgStartInSaucePan(al::HitSensor*, al::HitSensor*, bool);
bool sendMsgEndInSaucePan(al::HitSensor*, al::HitSensor*);
bool sendMsgLineDancerLink(al::HitSensor*, al::HitSensor*);
bool sendMsgLongPushSensorHit(al::HitSensor*, al::HitSensor*);
bool sendMsgLongPushBoxHit(al::HitSensor*, al::HitSensor*);
bool sendMsgGoldHammerAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgTrashBoxIn(al::HitSensor*, al::HitSensor*);
bool sendMsgTouchDoorDrumn(al::HitSensor*, al::HitSensor*);
bool sendMsgKuribo2DTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgKuriboCollisionDamage(al::HitSensor*, al::HitSensor*);
bool sendMsgKuriboCollisionKill(al::HitSensor*, al::HitSensor*);
bool sendMsgKuriboFlick(al::HitSensor*, al::HitSensor*);
bool sendMsgKuriboTowerOn(al::HitSensor*, al::HitSensor*, uint);
bool sendMsgPartyPopperSoundAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgYokinBallAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgYoshiDirectEat(al::HitSensor*, al::HitSensor*);
bool sendMsgYoshiTongueAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgYoshiTongueEatBind(al::HitSensor*, al::HitSensor*, float*, float*, float*);
bool sendMsgYoshiTongueEatBindCancel(al::HitSensor*, al::HitSensor*);
bool sendMsgYoshiTongueEatBindFinish(al::HitSensor*, al::HitSensor*);
bool sendMsgYoshiTongueEatHomingTarget(al::HitSensor*, al::HitSensor*);
bool sendMsgYukimaruPush(al::HitSensor*, al::HitSensor*);
bool sendMsgPunchMachinePunchStraight(al::HitSensor*, al::HitSensor*);
bool sendMsgPunchMachinePunchHook(al::HitSensor*, al::HitSensor*);
bool sendMsgPunchMachinePunchUpper(al::HitSensor*, al::HitSensor*);
bool sendMsgMorningStarWarpStart(al::HitSensor*, al::HitSensor*);
bool sendMsgMorningStarWarpEnd(al::HitSensor*, al::HitSensor*);
bool sendMsgGemyAim(al::HitSensor*, al::HitSensor*);
bool sendMsgHammerBrosHammerEnemyAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgHammerBrosHammerHackAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgHammerBrosHammerSearch(al::HitSensor*, al::HitSensor*);
bool sendMsgHackBrosContact(al::HitSensor*, al::HitSensor*);
bool sendMsgMotorcycleAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgMotorcycleCollideParkingLot(al::HitSensor*, al::HitSensor*);
bool sendMsgMotorcycleDashAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgMotorcycleDashCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgWanwanEnemyAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgWanwanPush(al::HitSensor*, al::HitSensor*);
bool sendMsgWanwanReboundAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgWanwanBlockAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgWanwanHoleIn(al::HitSensor*, al::HitSensor*);
bool sendMsgWaterRoadIn(al::HitSensor*, al::HitSensor*);
bool sendMsgWaterRoadNear(al::HitSensor*, al::HitSensor*);
bool sendMsgBreedaSlap(al::HitSensor*, al::HitSensor*);
bool sendMsgBreedaPush(al::HitSensor*, al::HitSensor*);
bool sendMsgGamaneBullet(al::HitSensor*, al::HitSensor*);
bool sendMsgGamaneBulletThrough(al::HitSensor*, al::HitSensor*);
bool sendMsgGamaneBulletForCoinFlower(al::HitSensor*, al::HitSensor*);
bool sendMsgVolleyballNpcScareByEnemy(al::HitSensor*, al::HitSensor*);
bool sendMsgRocketFlowerExtension(al::HitSensor*, al::HitSensor*);
bool sendMsgWanderBossCameraRange(al::HitSensor*, al::HitSensor*);
bool sendMsgKuriboGirlAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKuriboGirlLove(al::HitSensor*, al::HitSensor*);
bool sendMsgKuriboTop(al::HitSensor*, al::HitSensor*);
bool sendMsgTRexAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgTRexAttackCollideBody(al::HitSensor*, al::HitSensor*);
bool sendMsgTRexAttackCollideHead(al::HitSensor*, al::HitSensor*);
bool sendMsgTRexDashAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgTRexScrollPartsBreakWith(al::HitSensor*, al::HitSensor*);
bool sendMsgTsukkunNoTrace(al::HitSensor*, al::HitSensor*);
bool sendMsgTouchFireDrum2D(al::HitSensor*, al::HitSensor*);
bool sendMsgPropellerAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgTankExplosion(al::HitSensor*, al::HitSensor*);
bool sendMsgTankHackTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgUtsuboAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKillerAttackNoExplode(al::HitSensor*, al::HitSensor*);
bool sendMsgKillerMagnumAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgKillerMagnumHackAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgGabuzouAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgStackerRollingAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgStackerCapBoostAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgIgnoreIgnitionBomb(al::HitSensor*, al::HitSensor*);
bool sendMsgExplosionReflectBomb(al::HitSensor*, al::HitSensor*);
bool sendMsgGolemStampPress(al::HitSensor*, al::HitSensor*);
bool sendMsgSwitchOnWithSaveRequest(al::LiveActor*, SaveObjInfo*);
bool sendMsgWanwanReboundAttackToCollided(const al::LiveActor*, al::HitSensor*);
bool sendMsgWanwanBlockAttackToCollided(const al::LiveActor*, al::HitSensor*);
bool sendMsgDigPointSmell(al::HitSensor*, al::HitSensor*, struct DigPoint*);
bool sendMsgMofumofuBodyChainExplode(al::HitSensor*, al::HitSensor*, int);
bool sendMsgMoonBasementRockThroughCollision(al::HitSensor*, al::HitSensor*, bool);
bool sendMsgFishingWait(al::HitSensor*, al::HitSensor*, al::HitSensor*);
bool sendMsgFishingUpImmediately(al::HitSensor*, al::HitSensor*, const sead::Matrix34<float>&, const sead::Vector3<float>&, const char*);
bool sendMsgGunetterPush(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, float);
bool sendMsgTestPunch(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, int);
bool sendMsgTestPunchStrong(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, int);
bool sendMsgPunchGuard(al::HitSensor*, al::HitSensor*, int, int);
bool sendMsgTsukkunThrust(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, bool);
bool sendMsgTsukkunThrustSpin(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, bool);
bool sendMsgTsukkunThrustReflect(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, bool);
bool sendMsgTsukkunThrustCollide(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, bool);
bool sendMsgTsukkunThrustHitReflectCollide(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, bool);
bool sendMsgTsukkunThrustReflectCollide(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, int, bool);
bool sendMsgTsukkunThrustHole(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgTsukkunThroughCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgTsukkunHoldCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgTsukkunForceCancelCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgNetworkShootingShot(al::HitSensor*, al::HitSensor*, int);
bool sendMsgNetworkShootingChargeShot(al::HitSensor*, al::HitSensor*, int);
bool sendMsgRequestPlayerJumpBreakFloor(al::HitSensor*, al::HitSensor*);
bool sendMsgRequestPlayerJump(al::HitSensor*, al::HitSensor*, float);
bool sendMsgRequestPlayerTrampleJump(al::HitSensor*, al::HitSensor*, float);
bool sendMsgRequestPlayerSpinJump(al::HitSensor*, al::HitSensor*, float);
bool sendMsgRequestSphinxJump(al::HitSensor*, al::HitSensor*, float);
bool sendMsgIgnoreTouchTarget(al::HitSensor*, al::HitSensor*);
bool sendMsgIgnoreTouchTarget(al::ScreenPointer*, al::ScreenPointTarget*);
bool sendMsgInitTouchTargetInfo(al::HitSensor*, al::HitSensor*, struct TouchTargetInfo*, const sead::Vector3<float>*);
bool sendMsgInitTouchTargetInfo(al::ScreenPointer*, al::ScreenPointTarget*, TouchTargetInfo*, const sead::Vector3<float>*);
bool sendMsgCollisionImpulse(al::HitSensor*, al::HitSensor*, sead::Vector3<float>*, const sead::Vector3<float>&, float, const sead::Vector3<float>&,
                             float);
bool sendMsgWhipHold(al::HitSensor*, al::HitSensor*, struct WhipTargetInfo*);
bool sendMsgWhipBind(al::HitSensor*, al::HitSensor*, WhipTargetInfo*);
bool sendMsgWhipThrow(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgMagnet(al::HitSensor*, al::HitSensor*, bool);
bool sendMsgMagnetBulletAttack(al::HitSensor*, al::HitSensor*, float);
bool sendMsgDashPanel(al::HitSensor*, al::HitSensor*, int);
bool sendMsgTrampolineCrackJump(al::HitSensor*, al::HitSensor*, float, float);
bool sendMsgCapTouchWall(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgCapRethrow(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgCapRethrowReturnOnly(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&,
                                 const sead::Vector3<float>&);
bool sendMsgCapChangeGiant(al::HitSensor*, al::HitSensor*, float, int);
bool sendMsgPackunEatCancel(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgPackunEatEnd(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgPackunEatStartFollow(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>*);
bool sendMsgFireBlowerAttack(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&, float);
// bool sendMsgPaint(al::HitSensor *,al::HitSensor *,sead::Color4u8 const&,int,int);
bool sendMsgPaintTexture(al::HitSensor*, al::HitSensor*, int, float, int);
// bool sendMsgCheckPaintClear(al::HitSensor *,al::HitSensor *,sead::Color4u8
// const&,sead::Vector3<float> const&,int);
bool sendMsgCheckPaintAlpha(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgByugoBlow(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgHackDirectStageInit(al::HitSensor*, al::HitSensor*, IUsePlayerHack*);
bool sendMsgObjSnapForce(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgCapBeamerBeam(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiAttackCollide(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiAttackNoEffect(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiAttackStrong(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiTrample(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiTrampleReflect(al::HitSensor*, al::HitSensor*);
bool sendMsgHosuiTrampleReflectHigh(al::HitSensor*, al::HitSensor*);
bool sendMsgBubbleAttack(al::HitSensor*, al::HitSensor*);
bool sendMsgBubbleAttackToPecho(al::HitSensor*, al::HitSensor*);
bool sendMsgBubbleReflectH(al::HitSensor*, al::HitSensor*);
bool sendMsgBubbleReflectV(al::HitSensor*, al::HitSensor*);
bool sendMsgBubbleWallTouch(al::HitSensor*, al::HitSensor*);
bool sendMsgBubbleGroundTouchTrigger(al::HitSensor*, al::HitSensor*);
bool sendMsgBubbleLauncherStart(al::HitSensor*, al::HitSensor*);
bool sendMsgSenobiPartsMove(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, float);
bool sendMsgStampTo2D(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgAirExplosion(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgPushVelocity(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgGhostRecordStartOk(al::HitSensor*, al::HitSensor*, const char*);
bool sendMsgSandGeyserRaise(al::HitSensor*, al::HitSensor*, float, float);
bool sendMsgRaceWait(al::LiveActor*);
bool sendMsgRaceStart(al::LiveActor*);
bool sendMsgRaceStop(al::LiveActor*);
bool sendMsgRaceReturnToCourse(al::LiveActor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgPlayerLookAtPosition(al::HitSensor*, al::HitSensor*, sead::Vector3<float>*);
bool sendMsgTargetMarkerPosition(al::HitSensor*, al::HitSensor*, sead::Vector3<float>*);
bool sendMsgHackBlowJump(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, float);
bool sendMsgGolemStampPushV(al::HitSensor*, al::HitSensor*, float);
bool sendMsgGolemStampPushH(al::HitSensor*, al::HitSensor*, float);
bool sendMsgRequestPlayerWaitAnimDigPoint(al::HitSensor*, al::HitSensor*);
bool sendMsgEventFlowScareCheck(al::HitSensor*, al::HitSensor*, al::EventFlowExecutor*);
bool sendMsgPlayerItemGetAll(al::HitSensor*, al::HitSensor*);
bool sendMsgPlayerItemGetAll2D(al::HitSensor*, al::HitSensor*);
bool sendMsgTRexAttackAll(al::HitSensor*, al::HitSensor*);
bool sendMsgSeedTouch(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgSphinxRideAttackTouchThrough(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgSphinxRideAttackTouch(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&, const sead::Vector3<float>&);
bool sendMsgBlockUpperPunch2D(al::HitSensor*, al::HitSensor*);
bool sendMsgGotogotonOn(al::HitSensor*, al::HitSensor*);
bool sendMsgGotogotonGetJumpPath(al::HitSensor*, al::HitSensor*, al::ParabolicPath*);
bool sendMsgGotogotonGoalExist(al::HitSensor*, al::HitSensor*);
bool sendMsgGotogotonGoalMatch(al::HitSensor*, al::HitSensor*, struct GotogotonMark const*);
bool sendMsgBossMagmaBreathForce(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgBossMagmaCatchPlayer(al::HitSensor*, al::HitSensor*);
bool sendMsgBossMagmaReleasePlayer(al::HitSensor*, al::HitSensor*);
bool sendMsgBossMagmaDeadDemoStart(al::HitSensor*, al::HitSensor*);
bool sendMsgBossMagmaDeadDemoEnd(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgBossMagmaResetPos(al::HitSensor*, al::HitSensor*, const sead::Vector3<float>&);
bool sendMsgBossMagmaQueryToBubble(al::HitSensor*, al::HitSensor*);
bool sendMsgCheckFishingTarget(al::HitSensor*, al::HitSensor*, struct FishingFish const*);
bool sendMsgPushToPlayerAndKillVelocityToTarget(al::LiveActor*, al::HitSensor*, al::HitSensor*);
bool sendMsgPushToPlayerAndKillVelocityToTargetH(al::LiveActor*, al::HitSensor*, al::HitSensor*);
bool sendMsgInitCapTarget(al::HitSensor*, al::HitSensor*, struct CapTargetInfo const**);
bool sendMsgTransferHack(al::HitSensor*, al::HitSensor*);
bool sendMsgRequestTransferHack(al::HitSensor*, al::HitSensor*);
bool sendMsgInitHack(al::HitSensor*, al::HitSensor*);
bool sendMsgEndHack(al::HitSensor*, al::HitSensor*, const HackEndParam*);
bool sendMsgNpcScareByEnemy(al::HitSensor*, al::HitSensor*, int);
}  // namespace rs
