#pragma once

#include "sead/math/seadVector.h"

#include "al/actor/Placement.h"

#include "CameraPoser.h"

namespace alCameraPoserFunction {

struct CameraCollisionHitResult;

void initCameraArrowCollider(al::CameraPoser*);
void calcCameraPose(sead::Quat<float>*, const al::CameraPoser*);
void calcLookDir(sead::Vector3<float>*, const al::CameraPoser*);
void calcCameraDir(sead::Vector3<float>*, const al::CameraPoser*);
void calcCameraDirH(sead::Vector3<float>*, const al::CameraPoser*);
void calcLookDirH(sead::Vector3<float>*, const al::CameraPoser*);
void calcSideDir(sead::Vector3<float>*, const al::CameraPoser*);
void calcPreCameraDir(sead::Vector3<float>*, const al::CameraPoser*);
void calcPreCameraDirH(sead::Vector3<float>*, const al::CameraPoser*);
void calcPreLookDir(sead::Vector3<float>*, const al::CameraPoser*);
void calcPreLookDirH(sead::Vector3<float>*, const al::CameraPoser*);
void calcPreCameraAngleH(const al::CameraPoser*);
void calcPreCameraAngleV(const al::CameraPoser*);
void setLookAtPosToTarget(al::CameraPoser*);
void calcTargetTrans(sead::Vector3<float>*, const al::CameraPoser*);
void setLookAtPosToTargetAddOffset(al::CameraPoser*, const sead::Vector3<float>&);
void setCameraPosToTarget(al::CameraPoser*);
void setCameraPosToTargetAddOffset(al::CameraPoser*, const sead::Vector3<float>&);
void calcTargetTransWithOffset(sead::Vector3<float>*, const al::CameraPoser*);
void calcTargetVelocity(sead::Vector3<float>*, const al::CameraPoser*);
void calcTargetVelocityH(sead::Vector3<float>*, const al::CameraPoser*);
void calcTargetUp(sead::Vector3<float>*, const al::CameraPoser*);
void calcTargetSpeedV(const al::CameraPoser*);
void calcTargetPose(sead::Quat<float>*, const al::CameraPoser*);
void calcTargetFront(sead::Vector3<float>*, const al::CameraPoser*);
void calcTargetSide(sead::Vector3<float>*, const al::CameraPoser*);
void calcTargetGravity(sead::Vector3<float>*, const al::CameraPoser*);
void calcTargetSpeedH(const al::CameraPoser*);
void calcTargetJumpSpeed(const al::CameraPoser*);
void calcTargetFallSpeed(const al::CameraPoser*);
void tryGetTargetRequestDistance(float*, const al::CameraPoser*);
void tryGetBossDistanceCurve(const al::CameraPoser*);
void tryGetEquipmentDistanceCurve(const al::CameraPoser*);
void tryCalcSlopeCollisionDownFrontDirH(sead::Vector3<float>*, const al::CameraPoser*);
void checkValidTurnToSubTarget(const al::CameraPoser*);
void calcSubTargetBack(sead::Vector3<float>*, const al::CameraPoser*);
void calcSubTargetTrans(sead::Vector3<float>*, const al::CameraPoser*);
void calcSubTargetFront(sead::Vector3<float>*, const al::CameraPoser*);
void tryCalcSubTargetTurnBrakeDistanceRate(float*, const al::CameraPoser*);
void clampAngleSubTargetTurnRangeV(float*, const al::CameraPoser*);
void initCameraVerticalAbsorber(al::CameraPoser*);
void initCameraVerticalAbsorberNoCameraPosAbsorb(al::CameraPoser*);
void liberateVerticalAbsorb(al::CameraPoser*);
void stopUpdateVerticalAbsorb(al::CameraPoser*);
void stopUpdateVerticalAbsorbForSnapShotMode(al::CameraPoser*, const sead::Vector3<float>&);
void restartUpdateVerticalAbsorb(al::CameraPoser*);
void validateVerticalAbsorbKeepInFrame(al::CameraPoser*);
void invalidateVerticalAbsorbKeepInFrame(al::CameraPoser*);
void setVerticalAbsorbKeepInFrameScreenOffsetUp(al::CameraPoser*, float);
void setVerticalAbsorbKeepInFrameScreenOffsetDown(al::CameraPoser*, float);
void initCameraArrowCollider(al::CameraPoser*);
void initCameraArrowColliderWithoutThroughPassCollision(al::CameraPoser*);
void initCameraMoveLimit(al::CameraPoser*);
void initCameraAngleCtrl(al::CameraPoser*);
void initCameraAngleCtrlWithRelativeH(al::CameraPoser*);
void initCameraDefaultAngleRangeV(al::CameraPoser*, float, float);
void setCameraStartAngleV(al::CameraPoser*, float);
void setCameraAngleV(al::CameraPoser*, float);
void initAngleSwing(al::CameraPoser*);
void initCameraOffsetCtrlPreset(al::CameraPoser*);
void initGyroCameraCtrl(al::CameraPoser*);
void resetGyro(al::CameraPoser*);
void calcCameraGyroPose(const al::CameraPoser*, sead::Vector3<float>*, sead::Vector3<float>*, sead::Vector3<float>*);
void setGyroLimitAngleV(al::CameraPoser*, float, float);
void setGyroSensitivity(al::CameraPoser*, float, float);
void reduceGyroSencitivity(al::CameraPoser*);
void stopUpdateGyro(al::CameraPoser*);
void restartUpdateGyro(al::CameraPoser*);
void initSnapShotCameraCtrl(al::CameraPoser*);
void initSnapShotCameraCtrlZoomAutoReset(al::CameraPoser*);
void initSnapShotCameraCtrlZoomRollMove(al::CameraPoser*);
void validateSnapShotCameraLookAtOffset(al::CameraPoser*);
void validateSnapShotCameraZoomFovy(al::CameraPoser*);
void validateSnapShotCameraRoll(al::CameraPoser*);
void updateSnapShotCameraCtrl(al::CameraPoser*);
void startResetSnapShotCameraCtrl(al::CameraPoser*, int);
void setSnapShotMaxZoomOutFovyDegree(al::CameraPoser*, float);
void onVerticalAbsorb(al::CameraPoser*);
void offVerticalAbsorb(al::CameraPoser*);
void invalidateCameraBlur(al::CameraPoser*);
void validateCollider(al::CameraPoser*);
void invalidateCollider(al::CameraPoser*);
void validateCtrlSubjective(al::CameraPoser*);
void invalidateChangeSubjective(al::CameraPoser*);
void invalidateKeepDistanceNextCamera(al::CameraPoser*);
void invalidateKeepDistanceNextCameraIfNoCollide(al::CameraPoser*);
void invalidatePreCameraEndAfterInterpole(al::CameraPoser*);
void checkFirstCameraCollisionArrow(sead::Vector3<float>*, sead::Vector3<float>*, const al::IUseCollision*, const sead::Vector3<float>&,
                                    const sead::Vector3<float>&);
void checkFirstCameraCollisionArrow(alCameraPoserFunction::CameraCollisionHitResult*, const al::IUseCollision*, const sead::Vector3<float>&,
                                    const sead::Vector3<float>&);
void checkFirstCameraCollisionArrowOnlyCeiling(sead::Vector3<float>*, sead::Vector3<float>*, const al::IUseCollision*, const sead::Vector3<float>&,
                                               const sead::Vector3<float>&);
void checkCameraCollisionMoveSphere(sead::Vector3<float>*, const al::IUseCollision*, const sead::Vector3<float>&, const sead::Vector3<float>&, float);
void calcZoneRotateAngleH(float, const al::CameraPoser*);
void calcZoneRotateAngleH(float, const sead::Matrix34<float>&);
void calcZoneInvRotateAngleH(float, const sead::Matrix34<float>&);
void multVecZone(sead::Vector3<float>*, const sead::Vector3<float>&, const al::CameraPoser*);
void multVecInvZone(sead::Vector3<float>*, const sead::Vector3<float>&, const al::CameraPoser*);
void rotateVecZone(sead::Vector3<float>*, const sead::Vector3<float>&, const al::CameraPoser*);
void calcOffsetCameraKeepInFrameV(sead::Vector3<float>*, sead::LookAtCamera*, const sead::Vector3<float>&, const al::CameraPoser*, float, float);
void makeCameraKeepInFrameV(sead::LookAtCamera*, const sead::Vector3<float>&, const al::CameraPoser*, float, float);
void initCameraRail(al::CameraPoser*, const al::PlacementInfo&, const char*);
void tryGetCameraRailArg(float*, const al::PlacementInfo&, const char*, const char*);
void tryFindNearestLimitRailKeeper(const al::CameraPoser*, const sead::Vector3<float>&);
void calcCameraRotateStick(sead::Vector2<float>*, const al::CameraPoser*);
float calcCameraRotateStickH(const al::CameraPoser*);
float calcCameraRotateStickV(const al::CameraPoser*);
void calcCameraRotateStickPower(const al::CameraPoser*);
void tryCalcCameraSnapShotMoveStick(sead::Vector2<float>*, const al::CameraPoser*);

void getViewIndex(const al::CameraPoser*);
sead::LookAtCamera* getLookAtCamera(const al::CameraPoser*);
void getProjectionSead(const al::CameraPoser*);
void getProjection(const al::CameraPoser*);
void getProjectionMtx(const al::CameraPoser*);
void getNear(const al::CameraPoser*);
void getFar(const al::CameraPoser*);
void getAspect(const al::CameraPoser*);
void getPreCameraPos(const al::CameraPoser*);
sead::Vector3f* getPreLookAtPos(const al::CameraPoser*);
void getPreUpDir(const al::CameraPoser*);
void getPreFovyDegree(const al::CameraPoser*);
void getPreFovyRadian(const al::CameraPoser*);
void getPreCameraSwingAngleH(const al::CameraStartInfo&);
void getPreCameraSwingAngleV(const al::CameraStartInfo&);
void getPreCameraMaxSwingAngleH(const al::CameraStartInfo&);
void getPreCameraMaxSwingAngleV(const al::CameraStartInfo&);
void getAreaAngleH(const al::CameraStartInfo&);
void getAreaAngleV(const al::CameraStartInfo&);
void getNextAngleHByPreCamera(const al::CameraStartInfo&);
void getNextAngleVByPreCamera(const al::CameraStartInfo&);
void getUnderTargetCollisionPos(const al::CameraPoser*);
void getUnderTargetCollisionNormal(const al::CameraPoser*);
void getSlopeCollisionUpSpeed(const al::CameraPoser*);
void getSlopeCollisionDownSpeed(const al::CameraPoser*);
void getSubTargetRequestDistance(const al::CameraPoser*);
void getSubTargetTurnSpeedRate1(const al::CameraPoser*);
void getSubTargetTurnSpeedRate2(const al::CameraPoser*);
void getSubTargetTurnRestartStep(const al::CameraPoser*);
void getCameraVerticalAbsorbPosUp(const al::CameraPoser*);
void getCameraVerticalAbsorbPosDown(const al::CameraPoser*);
void getCameraAngleH(const al::CameraPoser*);
void getCameraAngleV(const al::CameraPoser*);
void getOffset(const al::CameraPoser*);
void getGyroFront(al::CameraPoser*);
void getGyroAngleV(al::CameraPoser*);
void getGyroAngleH(al::CameraPoser*);
void getSnapShotRollDegree(const al::CameraPoser*);
void getSnapShotLookAtOffset(const al::CameraPoser*);
void getRequestTargetAngleV(const al::CameraObjectRequestInfo&);
void getRequestAngleSpeed(const al::CameraObjectRequestInfo&);
void getRequestAngleV(const al::CameraObjectRequestInfo&);
void getCameraRailPointObjId(const al::CameraPoser*, int);
void getStickSensitivityLevel(const al::CameraPoser*);
void getStickSensitivityScale(const al::CameraPoser*);
void getGyroSensitivityLevel(const al::CameraPoser*);
void getGyroSensitivityScale(const al::CameraPoser*);

bool isPrePriorityDemo(const al::CameraStartInfo&);
bool isPrePriorityDemo2(const al::CameraStartInfo&);
bool isPrePriorityDemoTalk(const al::CameraStartInfo&);
bool isPrePriorityDemoAll(const al::CameraStartInfo&);
bool isPrePriorityEntranceAll(const al::CameraStartInfo&);
bool isPrePriorityPlayer(const al::CameraStartInfo&);
bool isEqualPreCameraName(const al::CameraStartInfo&, const char*);
bool isPreCameraFixAbsolute(const al::CameraStartInfo&);
bool isInvalidCollidePreCamera(const al::CameraStartInfo&);
bool isInvalidKeepPreCameraDistance(const al::CameraStartInfo&);
bool isInvalidKeepPreCameraDistanceIfNoCollide(const al::CameraStartInfo&);
bool isValidResetPreCameraPose(const al::CameraStartInfo&);
bool isValidKeepPreSelfCameraPose(const al::CameraStartInfo&);
bool isExistAreaAngleH(const al::CameraStartInfo&);
bool isExistAreaAngleV(const al::CameraStartInfo&);
bool isExistNextPoseByPreCamera(const al::CameraStartInfo&);
bool isChangeTarget(const al::CameraPoser*);
bool isExistCollisionUnderTarget(const al::CameraPoser*);
bool isExistSlopeCollisionUnderTarget(const al::CameraPoser*);
bool isExistWallCollisionUnderTarget(const al::CameraPoser*);
bool isExistSubTarget(const al::CameraPoser*);
bool isChangeSubTarget(const al::CameraPoser*);
bool isValidSubTargetTurnV(const al::CameraPoser*);
bool isValidSubTargetResetAfterTurnV(const al::CameraPoser*);
bool isValidAngleSwing(const al::CameraPoser*);
bool isStopUpdateGyro(const al::CameraPoser*);
bool isTargetCollideGround(const al::CameraPoser*);
bool isTargetInWater(const al::CameraPoser*);
bool isTargetInMoonGravity(const al::CameraPoser*);
bool isTargetClimbPole(const al::CameraPoser*);
bool isTargetGrabCeil(const al::CameraPoser*);
bool isTargetInvalidMoveByInput(const al::CameraPoser*);
bool isTargetEnableEndAfterInterpole(const al::CameraPoser*);
bool isTargetWallCatch(const al::CameraPoser*);
bool isSnapShotMode(const al::CameraPoser*);
bool isOffVerticalAbsorb(const al::CameraPoser*);
bool isRequestStopVerticalAbsorb(const al::CameraObjectRequestInfo&);
bool isRequestResetPosition(const al::CameraObjectRequestInfo&);
bool isRequestResetAngleV(const al::CameraObjectRequestInfo&);
bool isRequestDownToDefaultAngleBySpeed(const al::CameraObjectRequestInfo&);
bool isRequestUpToTargetAngleBySpeed(const al::CameraObjectRequestInfo&);
bool isRequestMoveDownAngleV(const al::CameraObjectRequestInfo&);
bool isRequestSetAngleV(const al::CameraObjectRequestInfo&);
bool isInvalidCollider(const al::CameraPoser*);
bool isInvalidPreCameraEndAfterInterpole(const al::CameraPoser*);
bool isSceneCameraFirstCalc(const al::CameraPoser*);
bool isActiveInterpole(const al::CameraPoser*);
bool isInvalidEndEntranceCamera(const al::CameraPoser*);
bool isPause(const al::CameraPoser*);
bool isValidGyro(const al::CameraPoser*);
bool isTriggerCameraResetRotate(const al::CameraPoser*);
bool isHoldCameraZoom(const al::CameraPoser*);
bool isHoldCameraSnapShotZoomIn(const al::CameraPoser*);
bool isHoldCameraSnapShotZoomOut(const al::CameraPoser*);
bool isHoldCameraSnapShotRollLeft(const al::CameraPoser*);
bool isHoldCameraSnapShotRollRight(const al::CameraPoser*);
bool isPlayerTypeFlyer(const al::CameraPoser*);
bool isPlayerTypeHighSpeedMove(const al::CameraPoser*);
bool isPlayerTypeHighJump(const al::CameraPoser*);
bool isPlayerTypeNotTouchGround(const al::CameraPoser*);
bool isOnRideObj(const al::CameraPoser*);
}  // namespace alCameraPoserFunction
